// Code generated by mojo. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.2
// source: armory/auth/v1/authing.proto

package auth

import (
	context "context"
	core "github.com/mojo-lang/mojo/go/pkg/mojo/core"
	auth "github.com/ncraft-io/armory/go/pkg/armory/auth"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Authing_CreateUser_FullMethodName       = "/armory.auth.v1.Authing/create_user"
	Authing_BatchCreateUsers_FullMethodName = "/armory.auth.v1.Authing/batch_create_users"
	Authing_UpdateUser_FullMethodName       = "/armory.auth.v1.Authing/update_user"
	Authing_ActiveUser_FullMethodName       = "/armory.auth.v1.Authing/active_user"
	Authing_GetUser_FullMethodName          = "/armory.auth.v1.Authing/get_user"
	Authing_ListUser_FullMethodName         = "/armory.auth.v1.Authing/list_user"
	Authing_DeleteUser_FullMethodName       = "/armory.auth.v1.Authing/delete_user"
	Authing_UpdatePassword_FullMethodName   = "/armory.auth.v1.Authing/update_password"
	Authing_Login_FullMethodName            = "/armory.auth.v1.Authing/login"
	Authing_Logout_FullMethodName           = "/armory.auth.v1.Authing/logout"
)

// AuthingClient is the client API for Authing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthingClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*auth.User, error)
	BatchCreateUsers(ctx context.Context, in *BatchCreateUsersRequest, opts ...grpc.CallOption) (*BatchCreateUsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*core.Null, error)
	ActiveUser(ctx context.Context, in *ActiveUserRequest, opts ...grpc.CallOption) (*auth.LogonUser, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*auth.User, error)
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*core.Null, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*core.Null, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*auth.LogonUser, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*core.Null, error)
}

type authingClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthingClient(cc grpc.ClientConnInterface) AuthingClient {
	return &authingClient{cc}
}

func (c *authingClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*auth.User, error) {
	out := new(auth.User)
	err := c.cc.Invoke(ctx, Authing_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) BatchCreateUsers(ctx context.Context, in *BatchCreateUsersRequest, opts ...grpc.CallOption) (*BatchCreateUsersResponse, error) {
	out := new(BatchCreateUsersResponse)
	err := c.cc.Invoke(ctx, Authing_BatchCreateUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*core.Null, error) {
	out := new(core.Null)
	err := c.cc.Invoke(ctx, Authing_UpdateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) ActiveUser(ctx context.Context, in *ActiveUserRequest, opts ...grpc.CallOption) (*auth.LogonUser, error) {
	out := new(auth.LogonUser)
	err := c.cc.Invoke(ctx, Authing_ActiveUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*auth.User, error) {
	out := new(auth.User)
	err := c.cc.Invoke(ctx, Authing_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, Authing_ListUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*core.Null, error) {
	out := new(core.Null)
	err := c.cc.Invoke(ctx, Authing_DeleteUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*core.Null, error) {
	out := new(core.Null)
	err := c.cc.Invoke(ctx, Authing_UpdatePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*auth.LogonUser, error) {
	out := new(auth.LogonUser)
	err := c.cc.Invoke(ctx, Authing_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authingClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*core.Null, error) {
	out := new(core.Null)
	err := c.cc.Invoke(ctx, Authing_Logout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthingServer is the server API for Authing service.
// All implementations must embed UnimplementedAuthingServer
// for forward compatibility
type AuthingServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*auth.User, error)
	BatchCreateUsers(context.Context, *BatchCreateUsersRequest) (*BatchCreateUsersResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*core.Null, error)
	ActiveUser(context.Context, *ActiveUserRequest) (*auth.LogonUser, error)
	GetUser(context.Context, *GetUserRequest) (*auth.User, error)
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*core.Null, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*core.Null, error)
	Login(context.Context, *LoginRequest) (*auth.LogonUser, error)
	Logout(context.Context, *LogoutRequest) (*core.Null, error)
	mustEmbedUnimplementedAuthingServer()
}

// UnimplementedAuthingServer must be embedded to have forward compatible implementations.
type UnimplementedAuthingServer struct {
}

func (UnimplementedAuthingServer) CreateUser(context.Context, *CreateUserRequest) (*auth.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAuthingServer) BatchCreateUsers(context.Context, *BatchCreateUsersRequest) (*BatchCreateUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreateUsers not implemented")
}
func (UnimplementedAuthingServer) UpdateUser(context.Context, *UpdateUserRequest) (*core.Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedAuthingServer) ActiveUser(context.Context, *ActiveUserRequest) (*auth.LogonUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveUser not implemented")
}
func (UnimplementedAuthingServer) GetUser(context.Context, *GetUserRequest) (*auth.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAuthingServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedAuthingServer) DeleteUser(context.Context, *DeleteUserRequest) (*core.Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedAuthingServer) UpdatePassword(context.Context, *UpdatePasswordRequest) (*core.Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedAuthingServer) Login(context.Context, *LoginRequest) (*auth.LogonUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthingServer) Logout(context.Context, *LogoutRequest) (*core.Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthingServer) mustEmbedUnimplementedAuthingServer() {}

// UnsafeAuthingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthingServer will
// result in compilation errors.
type UnsafeAuthingServer interface {
	mustEmbedUnimplementedAuthingServer()
}

func RegisterAuthingServer(s grpc.ServiceRegistrar, srv AuthingServer) {
	s.RegisterService(&Authing_ServiceDesc, srv)
}

func _Authing_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_BatchCreateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).BatchCreateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_BatchCreateUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).BatchCreateUsers(ctx, req.(*BatchCreateUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_ActiveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).ActiveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_ActiveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).ActiveUser(ctx, req.(*ActiveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_ListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authing_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthingServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authing_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthingServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authing_ServiceDesc is the grpc.ServiceDesc for Authing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "armory.auth.v1.Authing",
	HandlerType: (*AuthingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create_user",
			Handler:    _Authing_CreateUser_Handler,
		},
		{
			MethodName: "batch_create_users",
			Handler:    _Authing_BatchCreateUsers_Handler,
		},
		{
			MethodName: "update_user",
			Handler:    _Authing_UpdateUser_Handler,
		},
		{
			MethodName: "active_user",
			Handler:    _Authing_ActiveUser_Handler,
		},
		{
			MethodName: "get_user",
			Handler:    _Authing_GetUser_Handler,
		},
		{
			MethodName: "list_user",
			Handler:    _Authing_ListUser_Handler,
		},
		{
			MethodName: "delete_user",
			Handler:    _Authing_DeleteUser_Handler,
		},
		{
			MethodName: "update_password",
			Handler:    _Authing_UpdatePassword_Handler,
		},
		{
			MethodName: "login",
			Handler:    _Authing_Login_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _Authing_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "armory/auth/v1/authing.proto",
}
