// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: armory/auth/v1/authing.proto
// Protobuf Java Version: 4.33.4

package io.ncraft.armory.auth.v1;

/**
 * Protobuf type {@code armory.auth.v1.BatchCreateUsersResponse}
 */
@com.google.protobuf.Generated
public final class BatchCreateUsersResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:armory.auth.v1.BatchCreateUsersResponse)
    BatchCreateUsersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "BatchCreateUsersResponse");
  }
  // Use BatchCreateUsersResponse.newBuilder() to construct.
  private BatchCreateUsersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchCreateUsersResponse() {
    users_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.armory.auth.v1.AuthingProto.internal_static_armory_auth_v1_BatchCreateUsersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.armory.auth.v1.AuthingProto.internal_static_armory_auth_v1_BatchCreateUsersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.armory.auth.v1.BatchCreateUsersResponse.class, io.ncraft.armory.auth.v1.BatchCreateUsersResponse.Builder.class);
  }

  public static final int USERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.ncraft.armory.auth.User> users_;
  /**
   * <code>repeated .armory.auth.User users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.ncraft.armory.auth.User> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .armory.auth.User users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.ncraft.armory.auth.UserOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .armory.auth.User users = 1;</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .armory.auth.User users = 1;</code>
   */
  @java.lang.Override
  public io.ncraft.armory.auth.User getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .armory.auth.User users = 1;</code>
   */
  @java.lang.Override
  public io.ncraft.armory.auth.UserOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(1, users_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < users_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, users_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.armory.auth.v1.BatchCreateUsersResponse)) {
      return super.equals(obj);
    }
    io.ncraft.armory.auth.v1.BatchCreateUsersResponse other = (io.ncraft.armory.auth.v1.BatchCreateUsersResponse) obj;

    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.armory.auth.v1.BatchCreateUsersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code armory.auth.v1.BatchCreateUsersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:armory.auth.v1.BatchCreateUsersResponse)
      io.ncraft.armory.auth.v1.BatchCreateUsersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.armory.auth.v1.AuthingProto.internal_static_armory_auth_v1_BatchCreateUsersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.armory.auth.v1.AuthingProto.internal_static_armory_auth_v1_BatchCreateUsersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.armory.auth.v1.BatchCreateUsersResponse.class, io.ncraft.armory.auth.v1.BatchCreateUsersResponse.Builder.class);
    }

    // Construct using io.ncraft.armory.auth.v1.BatchCreateUsersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
      } else {
        users_ = null;
        usersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.armory.auth.v1.AuthingProto.internal_static_armory_auth_v1_BatchCreateUsersResponse_descriptor;
    }

    @java.lang.Override
    public io.ncraft.armory.auth.v1.BatchCreateUsersResponse getDefaultInstanceForType() {
      return io.ncraft.armory.auth.v1.BatchCreateUsersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.armory.auth.v1.BatchCreateUsersResponse build() {
      io.ncraft.armory.auth.v1.BatchCreateUsersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.armory.auth.v1.BatchCreateUsersResponse buildPartial() {
      io.ncraft.armory.auth.v1.BatchCreateUsersResponse result = new io.ncraft.armory.auth.v1.BatchCreateUsersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.ncraft.armory.auth.v1.BatchCreateUsersResponse result) {
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
    }

    private void buildPartial0(io.ncraft.armory.auth.v1.BatchCreateUsersResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.armory.auth.v1.BatchCreateUsersResponse) {
        return mergeFrom((io.ncraft.armory.auth.v1.BatchCreateUsersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.armory.auth.v1.BatchCreateUsersResponse other) {
      if (other == io.ncraft.armory.auth.v1.BatchCreateUsersResponse.getDefaultInstance()) return this;
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.ncraft.armory.auth.User m =
                  input.readMessage(
                      io.ncraft.armory.auth.User.parser(),
                      extensionRegistry);
              if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(m);
              } else {
                usersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.ncraft.armory.auth.User> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        users_ = new java.util.ArrayList<io.ncraft.armory.auth.User>(users_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.armory.auth.User, io.ncraft.armory.auth.User.Builder, io.ncraft.armory.auth.UserOrBuilder> usersBuilder_;

    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public java.util.List<io.ncraft.armory.auth.User> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public io.ncraft.armory.auth.User getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder setUsers(
        int index, io.ncraft.armory.auth.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder setUsers(
        int index, io.ncraft.armory.auth.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder addUsers(io.ncraft.armory.auth.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder addUsers(
        int index, io.ncraft.armory.auth.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder addUsers(
        io.ncraft.armory.auth.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder addUsers(
        int index, io.ncraft.armory.auth.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends io.ncraft.armory.auth.User> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public io.ncraft.armory.auth.User.Builder getUsersBuilder(
        int index) {
      return internalGetUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public io.ncraft.armory.auth.UserOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public java.util.List<? extends io.ncraft.armory.auth.UserOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public io.ncraft.armory.auth.User.Builder addUsersBuilder() {
      return internalGetUsersFieldBuilder().addBuilder(
          io.ncraft.armory.auth.User.getDefaultInstance());
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public io.ncraft.armory.auth.User.Builder addUsersBuilder(
        int index) {
      return internalGetUsersFieldBuilder().addBuilder(
          index, io.ncraft.armory.auth.User.getDefaultInstance());
    }
    /**
     * <code>repeated .armory.auth.User users = 1;</code>
     */
    public java.util.List<io.ncraft.armory.auth.User.Builder> 
         getUsersBuilderList() {
      return internalGetUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.armory.auth.User, io.ncraft.armory.auth.User.Builder, io.ncraft.armory.auth.UserOrBuilder> 
        internalGetUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.ncraft.armory.auth.User, io.ncraft.armory.auth.User.Builder, io.ncraft.armory.auth.UserOrBuilder>(
                users_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:armory.auth.v1.BatchCreateUsersResponse)
  }

  // @@protoc_insertion_point(class_scope:armory.auth.v1.BatchCreateUsersResponse)
  private static final io.ncraft.armory.auth.v1.BatchCreateUsersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.armory.auth.v1.BatchCreateUsersResponse();
  }

  public static io.ncraft.armory.auth.v1.BatchCreateUsersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchCreateUsersResponse>
      PARSER = new com.google.protobuf.AbstractParser<BatchCreateUsersResponse>() {
    @java.lang.Override
    public BatchCreateUsersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchCreateUsersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchCreateUsersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.armory.auth.v1.BatchCreateUsersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

