// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: armory/auth/v1/authing.proto
// Protobuf Java Version: 4.33.4

package io.ncraft.armory.auth.v1;

@com.google.protobuf.Generated
public interface BatchCreateUsersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:armory.auth.v1.BatchCreateUsersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string domain = 1;</code>
   * @return The domain.
   */
  java.lang.String getDomain();
  /**
   * <code>string domain = 1;</code>
   * @return The bytes for domain.
   */
  com.google.protobuf.ByteString
      getDomainBytes();

  /**
   * <code>repeated .armory.auth.User users = 2;</code>
   */
  java.util.List<io.ncraft.armory.auth.User> 
      getUsersList();
  /**
   * <code>repeated .armory.auth.User users = 2;</code>
   */
  io.ncraft.armory.auth.User getUsers(int index);
  /**
   * <code>repeated .armory.auth.User users = 2;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .armory.auth.User users = 2;</code>
   */
  java.util.List<? extends io.ncraft.armory.auth.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .armory.auth.User users = 2;</code>
   */
  io.ncraft.armory.auth.UserOrBuilder getUsersOrBuilder(
      int index);
}
