// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armory/unitable/v1/unitable.proto

package io.ncraft.armory.unitable.v1;

public interface BatchUpdateRowsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:armory.unitable.v1.BatchUpdateRowsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string database = 1;</code>
   * @return The database.
   */
  java.lang.String getDatabase();
  /**
   * <code>string database = 1;</code>
   * @return The bytes for database.
   */
  com.google.protobuf.ByteString
      getDatabaseBytes();

  /**
   * <code>string table = 2;</code>
   * @return The table.
   */
  java.lang.String getTable();
  /**
   * <code>string table = 2;</code>
   * @return The bytes for table.
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>repeated .mojo.core.Object rows = 4;</code>
   */
  java.util.List<org.mojolang.mojo.core.Object> 
      getRowsList();
  /**
   * <code>repeated .mojo.core.Object rows = 4;</code>
   */
  org.mojolang.mojo.core.Object getRows(int index);
  /**
   * <code>repeated .mojo.core.Object rows = 4;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .mojo.core.Object rows = 4;</code>
   */
  java.util.List<? extends org.mojolang.mojo.core.ObjectOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .mojo.core.Object rows = 4;</code>
   */
  org.mojolang.mojo.core.ObjectOrBuilder getRowsOrBuilder(
      int index);
}
