// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: armory/unitable/v1/unitable.proto
// Protobuf Java Version: 4.33.4

package io.ncraft.armory.unitable.v1;

@com.google.protobuf.Generated
public interface BatchCreateRowsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:armory.unitable.v1.BatchCreateRowsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.core.Object objects = 1;</code>
   */
  java.util.List<org.mojolang.mojo.core.Object> 
      getObjectsList();
  /**
   * <code>repeated .mojo.core.Object objects = 1;</code>
   */
  org.mojolang.mojo.core.Object getObjects(int index);
  /**
   * <code>repeated .mojo.core.Object objects = 1;</code>
   */
  int getObjectsCount();
  /**
   * <code>repeated .mojo.core.Object objects = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.core.ObjectOrBuilder> 
      getObjectsOrBuilderList();
  /**
   * <code>repeated .mojo.core.Object objects = 1;</code>
   */
  org.mojolang.mojo.core.ObjectOrBuilder getObjectsOrBuilder(
      int index);
}
