// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armory/unitable/v1/unitable.proto

package io.ncraft.armory.unitable.v1;

public interface DeleteTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:armory.unitable.v1.DeleteTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string database = 1;</code>
   * @return The database.
   */
  java.lang.String getDatabase();
  /**
   * <code>string database = 1;</code>
   * @return The bytes for database.
   */
  com.google.protobuf.ByteString
      getDatabaseBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bool force = 3;</code>
   * @return The force.
   */
  boolean getForce();
}
