// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armory/unitable/v1/unitable.proto

package io.ncraft.armory.unitable.v1;

public final class UnitableProto {
  private UnitableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_CreateTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_CreateTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_UpdateTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_UpdateTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_GetTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_GetTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListTablesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListTablesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListTablesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListTablesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_DeleteTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_DeleteTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_SyncTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_SyncTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_CreateColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_CreateColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_UpdateColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_UpdateColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_GetColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_GetColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_DeleteColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_DeleteColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListColumnsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListColumnsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListColumnsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListColumnsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_BatchCreateColumnsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_BatchCreateColumnsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_BatchUpdateColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_BatchUpdateColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_BatchDeleteColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_BatchDeleteColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_CreateRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_CreateRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_UpdateRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_UpdateRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_GetRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_GetRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_DeleteRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_DeleteRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListRowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListRowStatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListRowStatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ListRowStatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ListRowStatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ExportRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ExportRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_ExportRowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_ExportRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_BatchCreateRowsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_BatchCreateRowsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_BatchUpdateRowsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_BatchUpdateRowsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_armory_unitable_v1_BatchDeleteRowsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_armory_unitable_v1_BatchDeleteRowsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!armory/unitable/v1/unitable.proto\022\022arm" +
      "ory.unitable.v1\032\034armory/unitable/column." +
      "proto\032\033armory/unitable/table.proto\032\032mojo" +
      "/core/field_mask.proto\032\024mojo/core/null.p" +
      "roto\032\030mojo/core/ordering.proto\032\025mojo/cor" +
      "e/value.proto\032\017mojo/mojo.proto\"M\n\022Create" +
      "TableRequest\022\020\n\010database\030\001 \001(\t\022%\n\005table\030" +
      "\002 \001(\0132\026.armory.unitable.Table\"h\n\022UpdateT" +
      "ableRequest\022\020\n\010database\030\001 \001(\t\022%\n\005table\030\002" +
      " \001(\0132\026.armory.unitable.Table\022\n\n\002id\030\003 \001(\t" +
      "\022\r\n\005force\030\004 \001(\010\"/\n\017GetTableRequest\022\020\n\010da" +
      "tabase\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"\317\001\n\021ListTablesR" +
      "equest\022\020\n\010database\030\001 \001(\t\022\022\n\tpage_size\030\320\017" +
      " \001(\005\022\023\n\npage_token\030\321\017 \001(\t\022\r\n\004skip\030\322\017 \001(\005" +
      "\022\017\n\006filter\030\333\017 \001(\t\022#\n\005order\030\334\017 \001(\0132\023.mojo" +
      ".core.Ordering\022)\n\nfield_mask\030\335\017 \001(\0132\024.mo" +
      "jo.core.FieldMask\022\017\n\006unique\030\336\017 \001(\010\"l\n\022Li" +
      "stTablesResponse\022&\n\006tables\030\001 \003(\0132\026.armor" +
      "y.unitable.Table\022\024\n\013total_count\030\320\017 \001(\005\022\030" +
      "\n\017next_page_token\030\321\017 \001(\t\"A\n\022DeleteTableR" +
      "equest\022\020\n\010database\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\r\n\005" +
      "force\030\003 \001(\010\"0\n\020SyncTableRequest\022\020\n\010datab" +
      "ase\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"_\n\023CreateColumnReq" +
      "uest\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\'\n" +
      "\006column\030\003 \001(\0132\027.armory.unitable.Column\"k" +
      "\n\023UpdateColumnRequest\022\020\n\010database\030\001 \001(\t\022" +
      "\r\n\005table\030\002 \001(\t\022\'\n\006column\030\003 \001(\0132\027.armory." +
      "unitable.Column\022\n\n\002id\030\004 \001(\t\"?\n\020GetColumn" +
      "Request\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t" +
      "\022\n\n\002id\030\003 \001(\t\"B\n\023DeleteColumnRequest\022\020\n\010d" +
      "atabase\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\n\n\002id\030\003 \001(\t" +
      "\"\337\001\n\022ListColumnsRequest\022\020\n\010database\030\001 \001(" +
      "\t\022\r\n\005table\030\002 \001(\t\022\022\n\tpage_size\030\320\017 \001(\005\022\023\n\n" +
      "page_token\030\321\017 \001(\t\022\r\n\004skip\030\322\017 \001(\005\022\017\n\006filt" +
      "er\030\333\017 \001(\t\022#\n\005order\030\334\017 \001(\0132\023.mojo.core.Or" +
      "dering\022)\n\nfield_mask\030\335\017 \001(\0132\024.mojo.core." +
      "FieldMask\022\017\n\006unique\030\336\017 \001(\010\"o\n\023ListColumn" +
      "sResponse\022(\n\007columns\030\001 \003(\0132\027.armory.unit" +
      "able.Column\022\024\n\013total_count\030\320\017 \001(\005\022\030\n\017nex" +
      "t_page_token\030\321\017 \001(\t\"f\n\031BatchCreateColumn" +
      "sRequest\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(" +
      "\t\022(\n\007columns\030\003 \003(\0132\027.armory.unitable.Col" +
      "umn\"e\n\030BatchUpdateColumnRequest\022\020\n\010datab" +
      "ase\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022(\n\007columns\030\003 \003(" +
      "\0132\027.armory.unitable.Column\"H\n\030BatchDelet" +
      "eColumnRequest\022\020\n\010database\030\001 \001(\t\022\r\n\005tabl" +
      "e\030\002 \001(\t\022\013\n\003ids\030\003 \003(\t\"S\n\020CreateRowRequest" +
      "\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\036\n\003row" +
      "\030\003 \001(\0132\021.mojo.core.Object\"_\n\020UpdateRowRe" +
      "quest\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\n" +
      "\n\002id\030\003 \001(\t\022\036\n\003row\030\004 \001(\0132\021.mojo.core.Obje" +
      "ct\"<\n\rGetRowRequest\022\020\n\010database\030\001 \001(\t\022\r\n" +
      "\005table\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\"?\n\020DeleteRowReq" +
      "uest\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\n\n" +
      "\002id\030\003 \001(\t\"\352\001\n\016ListRowRequest\022\020\n\010database" +
      "\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\r\n\005query\030\003 \001(\t\022\022\n\t" +
      "page_size\030\320\017 \001(\005\022\023\n\npage_token\030\321\017 \001(\t\022\r\n" +
      "\004skip\030\322\017 \001(\005\022\017\n\006filter\030\333\017 \001(\t\022#\n\005order\030\334" +
      "\017 \001(\0132\023.mojo.core.Ordering\022)\n\nfield_mask" +
      "\030\335\017 \001(\0132\024.mojo.core.FieldMask\022\017\n\006unique\030" +
      "\336\017 \001(\010\"e\n\017ListRowResponse\022\"\n\007objects\030\001 \003" +
      "(\0132\021.mojo.core.Object\022\024\n\013total_count\030\320\017 " +
      "\001(\005\022\030\n\017next_page_token\030\321\017 \001(\t\"\356\001\n\022ListRo" +
      "wStatRequest\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030" +
      "\002 \001(\t\022\r\n\005stats\030\003 \003(\t\022\022\n\tpage_size\030\320\017 \001(\005" +
      "\022\023\n\npage_token\030\321\017 \001(\t\022\r\n\004skip\030\322\017 \001(\005\022\017\n\006" +
      "filter\030\333\017 \001(\t\022#\n\005order\030\334\017 \001(\0132\023.mojo.cor" +
      "e.Ordering\022)\n\nfield_mask\030\335\017 \001(\0132\024.mojo.c" +
      "ore.FieldMask\022\017\n\006unique\030\336\017 \001(\010\"i\n\023ListRo" +
      "wStatResponse\022\"\n\007objects\030\001 \003(\0132\021.mojo.co" +
      "re.Object\022\024\n\013total_count\030\320\017 \001(\005\022\030\n\017next_" +
      "page_token\030\321\017 \001(\t\"\335\001\n\020ExportRowRequest\022\020" +
      "\n\010database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\022\n\tpage_" +
      "size\030\320\017 \001(\005\022\023\n\npage_token\030\321\017 \001(\t\022\r\n\004skip" +
      "\030\322\017 \001(\005\022\017\n\006filter\030\333\017 \001(\t\022#\n\005order\030\334\017 \001(\013" +
      "2\023.mojo.core.Ordering\022)\n\nfield_mask\030\335\017 \001" +
      "(\0132\024.mojo.core.FieldMask\022\017\n\006unique\030\336\017 \001(" +
      "\010\"g\n\021ExportRowResponse\022\"\n\007objects\030\001 \003(\0132" +
      "\021.mojo.core.Object\022\024\n\013total_count\030\320\017 \001(\005" +
      "\022\030\n\017next_page_token\030\321\017 \001(\t\"Z\n\026BatchCreat" +
      "eRowsRequest\022\020\n\010database\030\001 \001(\t\022\r\n\005table\030" +
      "\002 \001(\t\022\037\n\004rows\030\003 \003(\0132\021.mojo.core.Object\"Z" +
      "\n\026BatchUpdateRowsRequest\022\020\n\010database\030\001 \001" +
      "(\t\022\r\n\005table\030\002 \001(\t\022\037\n\004rows\030\004 \003(\0132\021.mojo.c" +
      "ore.Object\"F\n\026BatchDeleteRowsRequest\022\020\n\010" +
      "database\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\013\n\003ids\030\003 \003" +
      "(\t2\225\017\n\010Unitable\022N\n\014create_table\022&.armory" +
      ".unitable.v1.CreateTableRequest\032\026.armory" +
      ".unitable.Table\022G\n\014update_table\022&.armory" +
      ".unitable.v1.UpdateTableRequest\032\017.mojo.c" +
      "ore.Null\022H\n\tget_table\022#.armory.unitable." +
      "v1.GetTableRequest\032\026.armory.unitable.Tab" +
      "le\022\\\n\013list_tables\022%.armory.unitable.v1.L" +
      "istTablesRequest\032&.armory.unitable.v1.Li" +
      "stTablesResponse\022G\n\014delete_table\022&.armor" +
      "y.unitable.v1.DeleteTableRequest\032\017.mojo." +
      "core.Null\022J\n\nsync_table\022$.armory.unitabl" +
      "e.v1.SyncTableRequest\032\026.armory.unitable." +
      "Table\022Q\n\rcreate_column\022\'.armory.unitable" +
      ".v1.CreateColumnRequest\032\027.armory.unitabl" +
      "e.Column\022I\n\rupdate_column\022\'.armory.unita" +
      "ble.v1.UpdateColumnRequest\032\017.mojo.core.N" +
      "ull\022K\n\nget_column\022$.armory.unitable.v1.G" +
      "etColumnRequest\032\027.armory.unitable.Column" +
      "\022I\n\rdelete_column\022\'.armory.unitable.v1.D" +
      "eleteColumnRequest\032\017.mojo.core.Null\022_\n\014l" +
      "ist_columns\022&.armory.unitable.v1.ListCol" +
      "umnsRequest\032\'.armory.unitable.v1.ListCol" +
      "umnsResponse\022V\n\024batch_create_columns\022-.a" +
      "rmory.unitable.v1.BatchCreateColumnsRequ" +
      "est\032\017.mojo.core.Null\022T\n\023batch_update_col" +
      "umn\022,.armory.unitable.v1.BatchUpdateColu" +
      "mnRequest\032\017.mojo.core.Null\022T\n\023batch_dele" +
      "te_column\022,.armory.unitable.v1.BatchDele" +
      "teColumnRequest\032\017.mojo.core.Null\022E\n\ncrea" +
      "te_row\022$.armory.unitable.v1.CreateRowReq" +
      "uest\032\021.mojo.core.Object\022C\n\nupdate_row\022$." +
      "armory.unitable.v1.UpdateRowRequest\032\017.mo" +
      "jo.core.Null\022?\n\007get_row\022!.armory.unitabl" +
      "e.v1.GetRowRequest\032\021.mojo.core.Object\022C\n" +
      "\ndelete_row\022$.armory.unitable.v1.DeleteR" +
      "owRequest\032\017.mojo.core.Null\022S\n\010list_row\022\"" +
      ".armory.unitable.v1.ListRowRequest\032#.arm" +
      "ory.unitable.v1.ListRowResponse\022`\n\rlist_" +
      "row_stat\022&.armory.unitable.v1.ListRowSta" +
      "tRequest\032\'.armory.unitable.v1.ListRowSta" +
      "tResponse\022Y\n\nexport_row\022$.armory.unitabl" +
      "e.v1.ExportRowRequest\032%.armory.unitable." +
      "v1.ExportRowResponse\022P\n\021batch_create_row" +
      "s\022*.armory.unitable.v1.BatchCreateRowsRe" +
      "quest\032\017.mojo.core.Null\022P\n\021batch_update_r" +
      "ows\022*.armory.unitable.v1.BatchUpdateRows" +
      "Request\032\017.mojo.core.Null\022P\n\021batch_delete" +
      "_rows\022*.armory.unitable.v1.BatchDeleteRo" +
      "wsRequest\032\017.mojo.core.NullBo\n\034io.ncraft." +
      "armory.unitable.v1B\rUnitableProtoP\001Z>git" +
      "hub.com/ncraft-io/armory/go/pkg/armory/u" +
      "nitable/v1;unitableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.ncraft.armory.unitable.ColumnProto.getDescriptor(),
          io.ncraft.armory.unitable.TableProto.getDescriptor(),
          org.mojolang.mojo.core.FieldMaskProto.getDescriptor(),
          org.mojolang.mojo.core.NullProto.getDescriptor(),
          org.mojolang.mojo.core.OrderingProto.getDescriptor(),
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          org.mojolang.mojo.MojoProtos.getDescriptor(),
        });
    internal_static_armory_unitable_v1_CreateTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_armory_unitable_v1_CreateTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_CreateTableRequest_descriptor,
        new java.lang.String[] { "Database", "Table", });
    internal_static_armory_unitable_v1_UpdateTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_armory_unitable_v1_UpdateTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_UpdateTableRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Id", "Force", });
    internal_static_armory_unitable_v1_GetTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_armory_unitable_v1_GetTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_GetTableRequest_descriptor,
        new java.lang.String[] { "Database", "Id", });
    internal_static_armory_unitable_v1_ListTablesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_armory_unitable_v1_ListTablesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListTablesRequest_descriptor,
        new java.lang.String[] { "Database", "PageSize", "PageToken", "Skip", "Filter", "Order", "FieldMask", "Unique", });
    internal_static_armory_unitable_v1_ListTablesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_armory_unitable_v1_ListTablesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListTablesResponse_descriptor,
        new java.lang.String[] { "Tables", "TotalCount", "NextPageToken", });
    internal_static_armory_unitable_v1_DeleteTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_armory_unitable_v1_DeleteTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_DeleteTableRequest_descriptor,
        new java.lang.String[] { "Database", "Id", "Force", });
    internal_static_armory_unitable_v1_SyncTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_armory_unitable_v1_SyncTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_SyncTableRequest_descriptor,
        new java.lang.String[] { "Database", "Id", });
    internal_static_armory_unitable_v1_CreateColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_armory_unitable_v1_CreateColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_CreateColumnRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Column", });
    internal_static_armory_unitable_v1_UpdateColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_armory_unitable_v1_UpdateColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_UpdateColumnRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Column", "Id", });
    internal_static_armory_unitable_v1_GetColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_armory_unitable_v1_GetColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_GetColumnRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Id", });
    internal_static_armory_unitable_v1_DeleteColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_armory_unitable_v1_DeleteColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_DeleteColumnRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Id", });
    internal_static_armory_unitable_v1_ListColumnsRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_armory_unitable_v1_ListColumnsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListColumnsRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "PageSize", "PageToken", "Skip", "Filter", "Order", "FieldMask", "Unique", });
    internal_static_armory_unitable_v1_ListColumnsResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_armory_unitable_v1_ListColumnsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListColumnsResponse_descriptor,
        new java.lang.String[] { "Columns", "TotalCount", "NextPageToken", });
    internal_static_armory_unitable_v1_BatchCreateColumnsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_armory_unitable_v1_BatchCreateColumnsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_BatchCreateColumnsRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Columns", });
    internal_static_armory_unitable_v1_BatchUpdateColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_armory_unitable_v1_BatchUpdateColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_BatchUpdateColumnRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Columns", });
    internal_static_armory_unitable_v1_BatchDeleteColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_armory_unitable_v1_BatchDeleteColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_BatchDeleteColumnRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Ids", });
    internal_static_armory_unitable_v1_CreateRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_armory_unitable_v1_CreateRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_CreateRowRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Row", });
    internal_static_armory_unitable_v1_UpdateRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_armory_unitable_v1_UpdateRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_UpdateRowRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Id", "Row", });
    internal_static_armory_unitable_v1_GetRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_armory_unitable_v1_GetRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_GetRowRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Id", });
    internal_static_armory_unitable_v1_DeleteRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_armory_unitable_v1_DeleteRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_DeleteRowRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Id", });
    internal_static_armory_unitable_v1_ListRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_armory_unitable_v1_ListRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListRowRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Query", "PageSize", "PageToken", "Skip", "Filter", "Order", "FieldMask", "Unique", });
    internal_static_armory_unitable_v1_ListRowResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_armory_unitable_v1_ListRowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListRowResponse_descriptor,
        new java.lang.String[] { "Objects", "TotalCount", "NextPageToken", });
    internal_static_armory_unitable_v1_ListRowStatRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_armory_unitable_v1_ListRowStatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListRowStatRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Stats", "PageSize", "PageToken", "Skip", "Filter", "Order", "FieldMask", "Unique", });
    internal_static_armory_unitable_v1_ListRowStatResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_armory_unitable_v1_ListRowStatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ListRowStatResponse_descriptor,
        new java.lang.String[] { "Objects", "TotalCount", "NextPageToken", });
    internal_static_armory_unitable_v1_ExportRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_armory_unitable_v1_ExportRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ExportRowRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "PageSize", "PageToken", "Skip", "Filter", "Order", "FieldMask", "Unique", });
    internal_static_armory_unitable_v1_ExportRowResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_armory_unitable_v1_ExportRowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_ExportRowResponse_descriptor,
        new java.lang.String[] { "Objects", "TotalCount", "NextPageToken", });
    internal_static_armory_unitable_v1_BatchCreateRowsRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_armory_unitable_v1_BatchCreateRowsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_BatchCreateRowsRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Rows", });
    internal_static_armory_unitable_v1_BatchUpdateRowsRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_armory_unitable_v1_BatchUpdateRowsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_BatchUpdateRowsRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Rows", });
    internal_static_armory_unitable_v1_BatchDeleteRowsRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_armory_unitable_v1_BatchDeleteRowsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_armory_unitable_v1_BatchDeleteRowsRequest_descriptor,
        new java.lang.String[] { "Database", "Table", "Ids", });
    io.ncraft.armory.unitable.ColumnProto.getDescriptor();
    io.ncraft.armory.unitable.TableProto.getDescriptor();
    org.mojolang.mojo.core.FieldMaskProto.getDescriptor();
    org.mojolang.mojo.core.NullProto.getDescriptor();
    org.mojolang.mojo.core.OrderingProto.getDescriptor();
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    org.mojolang.mojo.MojoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
