// Code generated by ncraft. DO NOT EDIT.
// Rerunning ncraft will overwrite this file.
// Version: 0.1.0
// Version Date:

package server

import (
	"context"
	"errors"
	"fmt"
	"github.com/gorilla/mux"
	"net"

	"github.com/rs/cors"
	"net/http"
	"net/http/pprof"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	// 3d Party
	"github.com/etherlabsio/healthcheck/v2"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"google.golang.org/grpc"

	"github.com/ncraft-io/ncraft/go/pkg/gokit/utils/network"
	_ "go.uber.org/automaxprocs"

	nclient "github.com/ncraft-io/ncraft/go/pkg/gokit/client"
	"github.com/ncraft-io/ncraft/go/pkg/ncraft/logs"

	"github.com/ncraft-io/ncraft/go/pkg/gokit/kit"
	"github.com/ncraft-io/ncraft/go/pkg/gokit/metrics"
	"github.com/ncraft-io/ncraft/go/pkg/gokit/sd"
	nserver "github.com/ncraft-io/ncraft/go/pkg/gokit/server"
	"github.com/ncraft-io/ncraft/go/pkg/gokit/tracing"

	kitprometheus "github.com/go-kit/kit/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"

	"github.com/ncraft-io/armory/service-go/pkg/unitable-service/handlers"
	"github.com/ncraft-io/armory/service-go/pkg/unitable-service/svc"

	// This Service api
	pb "github.com/ncraft-io/armory/go/pkg/armory/unitable/v1"
)

var _ nclient.Config

const FullServiceName = "armory.unitable.v1.Unitable"

func NewEndpoints(options map[string]interface{}, services ...pb.UnitableServer) svc.Endpoints {
	// Business domain.
	var service pb.UnitableServer
	{
		if len(services) > 0 {
			service = services[0]
		} else {
			service = handlers.NewService()
		}
		// Wrap Service with middlewares. See handlers/middlewares.go
		service = handlers.WrapService(service, options)
	}

	// Endpoint domain.
	var (
		listDatabasesEndpoint      = svc.MakeListDatabasesEndpoint(service)
		createTableEndpoint        = svc.MakeCreateTableEndpoint(service)
		updateTableEndpoint        = svc.MakeUpdateTableEndpoint(service)
		getTableEndpoint           = svc.MakeGetTableEndpoint(service)
		listTablesEndpoint         = svc.MakeListTablesEndpoint(service)
		deleteTableEndpoint        = svc.MakeDeleteTableEndpoint(service)
		syncTableEndpoint          = svc.MakeSyncTableEndpoint(service)
		createColumnEndpoint       = svc.MakeCreateColumnEndpoint(service)
		updateColumnEndpoint       = svc.MakeUpdateColumnEndpoint(service)
		getColumnEndpoint          = svc.MakeGetColumnEndpoint(service)
		deleteColumnEndpoint       = svc.MakeDeleteColumnEndpoint(service)
		listColumnsEndpoint        = svc.MakeListColumnsEndpoint(service)
		batchCreateColumnsEndpoint = svc.MakeBatchCreateColumnsEndpoint(service)
		batchUpdateColumnEndpoint  = svc.MakeBatchUpdateColumnEndpoint(service)
		batchDeleteColumnEndpoint  = svc.MakeBatchDeleteColumnEndpoint(service)
		createRowEndpoint          = svc.MakeCreateRowEndpoint(service)
		updateRowEndpoint          = svc.MakeUpdateRowEndpoint(service)
		getRowEndpoint             = svc.MakeGetRowEndpoint(service)
		batchGetRowEndpoint        = svc.MakeBatchGetRowEndpoint(service)
		deleteRowEndpoint          = svc.MakeDeleteRowEndpoint(service)
		listRowEndpoint            = svc.MakeListRowEndpoint(service)
		getRowStatEndpoint         = svc.MakeGetRowStatEndpoint(service)
		exportRowEndpoint          = svc.MakeExportRowEndpoint(service)
		batchCreateRowsEndpoint    = svc.MakeBatchCreateRowsEndpoint(service)
		batchUpdateRowsEndpoint    = svc.MakeBatchUpdateRowsEndpoint(service)
		batchDeleteRowsEndpoint    = svc.MakeBatchDeleteRowsEndpoint(service)
		createDbQueryEndpoint      = svc.MakeCreateDbQueryEndpoint(service)
		updateDbQueryEndpoint      = svc.MakeUpdateDbQueryEndpoint(service)
		getDbQueryEndpoint         = svc.MakeGetDbQueryEndpoint(service)
		listDbQueriesEndpoint      = svc.MakeListDbQueriesEndpoint(service)
		deleteDbQueryEndpoint      = svc.MakeDeleteDbQueryEndpoint(service)
		runDbQueryEndpoint         = svc.MakeRunDbQueryEndpoint(service)
	)

	endpoints := svc.Endpoints{
		ListDatabasesEndpoint:      listDatabasesEndpoint,
		CreateTableEndpoint:        createTableEndpoint,
		UpdateTableEndpoint:        updateTableEndpoint,
		GetTableEndpoint:           getTableEndpoint,
		ListTablesEndpoint:         listTablesEndpoint,
		DeleteTableEndpoint:        deleteTableEndpoint,
		SyncTableEndpoint:          syncTableEndpoint,
		CreateColumnEndpoint:       createColumnEndpoint,
		UpdateColumnEndpoint:       updateColumnEndpoint,
		GetColumnEndpoint:          getColumnEndpoint,
		DeleteColumnEndpoint:       deleteColumnEndpoint,
		ListColumnsEndpoint:        listColumnsEndpoint,
		BatchCreateColumnsEndpoint: batchCreateColumnsEndpoint,
		BatchUpdateColumnEndpoint:  batchUpdateColumnEndpoint,
		BatchDeleteColumnEndpoint:  batchDeleteColumnEndpoint,
		CreateRowEndpoint:          createRowEndpoint,
		UpdateRowEndpoint:          updateRowEndpoint,
		GetRowEndpoint:             getRowEndpoint,
		BatchGetRowEndpoint:        batchGetRowEndpoint,
		DeleteRowEndpoint:          deleteRowEndpoint,
		ListRowEndpoint:            listRowEndpoint,
		GetRowStatEndpoint:         getRowStatEndpoint,
		ExportRowEndpoint:          exportRowEndpoint,
		BatchCreateRowsEndpoint:    batchCreateRowsEndpoint,
		BatchUpdateRowsEndpoint:    batchUpdateRowsEndpoint,
		BatchDeleteRowsEndpoint:    batchDeleteRowsEndpoint,
		CreateDbQueryEndpoint:      createDbQueryEndpoint,
		UpdateDbQueryEndpoint:      updateDbQueryEndpoint,
		GetDbQueryEndpoint:         getDbQueryEndpoint,
		ListDbQueriesEndpoint:      listDbQueriesEndpoint,
		DeleteDbQueryEndpoint:      deleteDbQueryEndpoint,
		RunDbQueryEndpoint:         runDbQueryEndpoint,
	}

	// Wrap selected Endpoints with middlewares. See handlers/middlewares.go
	endpoints = handlers.WrapEndpoints(endpoints, options)

	return endpoints
}

func RegisterService(cfg nserver.Config, r *mux.Router, s *grpc.Server, services ...pb.UnitableServer) svc.Endpoints {
	// tracing init
	tracer, c := tracing.New(FullServiceName)
	if c != nil {
		defer c.Close()
	}

	// Create a single logger, which we'll use and give to other components.
	logger := kit.Logger()

	options := map[string]interface{}{
		"tracer": tracer,
		"logger": logger,
	}

	metricsConfig := metrics.NewConfig("metrics")
	if metricsConfig.Enabled() {
		fieldKeys := []string{"method", "access_key", "error"}
		count := kitprometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: metricsConfig.Department,
			Subsystem: metricsConfig.Project,
			Name:      "request_count",
			Help:      "Number of requests received.",
		}, fieldKeys)

		latency := kitprometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: metricsConfig.Department,
			Subsystem: metricsConfig.Project,
			Name:      "request_latency_seconds",
			Help:      "Total duration of requests in seconds.",
		}, fieldKeys)

		options["count"] = count
		options["latency"] = latency
	}

	var service pb.UnitableServer
	if len(services) > 0 {
		service = services[0]
	} else {
		service = handlers.NewService()
	}
	// Optional custom routes live in the handlers package, which regeneration preserves.
	// Register them before generated routes so specialized transports can take precedence.
	if registrar, ok := service.(interface{ RegisterHTTPHandlers(*mux.Router) }); ok {
		registrar.RegisterHTTPHandlers(r)
	}
	endpoints := NewEndpoints(options, service)

	svc.RegisterHttpHandler(r, endpoints, tracer, logger)
	pb.RegisterUnitableServer(s, svc.MakeGRPCServer(endpoints, tracer, logger))

	return endpoints
}

// Run starts a new http server, gRPC server, and a debug server with the
// passed config and logger
func Run(cfg nserver.Config) {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	// Each transport can report once without blocking during shutdown.
	errc := make(chan error, 3)
	service := handlers.NewService()
	services := []interface{}{service}
	var started []interface{}

	s := grpc.NewServer(grpc.UnaryInterceptor(unaryServerFilter))
	r := mux.NewRouter()
	httpServer := &http.Server{Addr: cfg.HttpAddr, Handler: cors.AllowAll().Handler(r)}
	m := http.NewServeMux()
	m.Handle("/debug/pprof/", http.HandlerFunc(pprof.Index))
	m.Handle("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
	m.Handle("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
	m.Handle("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
	m.Handle("/debug/pprof/trace", http.HandlerFunc(pprof.Trace))

	m.Handle("/metrics", promhttp.Handler())

	m.Handle("/health", healthcheck.Handler(
		// WithTimeout allows you to set a max overall timeout.
		healthcheck.WithTimeout(5*time.Second),
		healthcheck.WithChecker("alive", healthcheck.CheckerFunc(func(ctx context.Context) error {
			conn, err := net.DialTimeout("tcp", cfg.HttpAddr, time.Second)
			if err != nil {
				return err
			}
			return conn.Close()
		})),
	))

	debugServer := &http.Server{Addr: cfg.DebugAddr, Handler: m}

	// Stop transports before releasing dependencies used by in-flight requests.
	// Successfully started services shut down in reverse order, including after
	// partial startup failure. A failing Start must clean up its own resources.
	defer func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), nserver.DefaultShutdownTimeout)
		defer cancel()
		if err := nserver.ShutdownServers(shutdownCtx, s, httpServer, debugServer); err != nil {
			logs.Errorw("shutdown transports", "error", err)
		}
		for i := len(started) - 1; i >= 0; i-- {
			if shutdowner, ok := started[i].(nserver.Shutdowner); ok {
				if err := shutdowner.Shutdown(shutdownCtx); err != nil {
					logs.Errorw("shutdown service", "service", fmt.Sprintf("%T", started[i]), "error", err)
				}
			}
		}
		logs.Info("unitable.UnitableServer", " closed.")
	}()

	for _, service := range services {
		if starter, ok := service.(nserver.Starter); ok {
			if err := starter.Start(cfg); err != nil {
				logs.Errorw("start service", "service", fmt.Sprintf("%T", service), "error", err)
				return
			}
		}
		started = append(started, service)
	}
	endpoints := RegisterService(cfg, r, s, service)

	// Bind all listeners before accepting requests; roll back on any bind error.
	httpListener, err := net.Listen("tcp", cfg.HttpAddr)
	if err != nil {
		logs.Errorw("listen HTTP", "error", err)
		return
	}
	defer httpListener.Close()
	grpcListener, err := net.Listen("tcp", cfg.GrpcAddr)
	if err != nil {
		logs.Errorw("listen gRPC", "error", err)
		return
	}
	defer grpcListener.Close()
	debugListener, err := net.Listen("tcp", cfg.DebugAddr)
	if err != nil {
		logs.Errorw("listen debug", "error", err)
		return
	}
	defer debugListener.Close()

	// HTTP transport.
	go func() {
		logs.Infow("begin http server", "transport", "HTTP", "address", cfg.HttpAddr)
		if err := httpServer.Serve(httpListener); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errc <- fmt.Errorf("HTTP server: %w", err)
		}
	}()
	// gRPC transport.
	go func() {
		logs.Infow("begin grpc server", "transport", "gRPC", "address", cfg.GrpcAddr)
		if err := s.Serve(grpcListener); err != nil && !errors.Is(err, grpc.ErrServerStopped) {
			errc <- fmt.Errorf("gRPC server: %w", err)
		}
	}()
	// Debug transport.
	go func() {
		logs.Infow("begin debug server", "transport", "debug", "address", cfg.DebugAddr)
		if err := debugServer.Serve(debugListener); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errc <- fmt.Errorf("debug server: %w", err)
		}
	}()
	_ = endpoints

	sdConfig := sd.NewConfig("sd")
	sdClient := sd.New(sdConfig, kit.Logger())
	if sdClient != nil {
		addr := cfg.GrpcAddr
		if strings.ToLower(sdConfig.Transport) == "http" {
			addr = cfg.HttpAddr
		}
		url := network.GetHost() + ":" + getServerPort(addr)
		err := sdClient.Register(url, FullServiceName, []string{})
		if err != nil {
			logs.Errorw("register service discovery", "error", err)
			return
		}
		defer sdClient.Deregister()
	}

	logs.Info("unitable.UnitableServer", " started.")
	// ErrorSource channels are service-owned; nil/closed channels and nil errors
	// are ignored. Cancellation is a normal shutdown, not a service failure.
	if err := nserver.WaitForError(ctx, errc, started...); err != nil {
		logs.Errorw("server stopped after an error", "error", err)
	}
}

func getServerPort(addr string) string {
	host := strings.Split(addr, ":")
	if len(host) < 2 {
		panic("host name is invalid (" + addr + ")")
	}
	return host[1]
}

func unaryServerFilter(ctx context.Context, req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler) (resp interface{}, err error) {
	//if err := middleware.Validate(req); err != nil {
	//	logs.Errorf("validate request failed, err: %s", err)
	//	return nil, core.NewError(http.StatusBadRequest, err.Error())
	//}

	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic: %v", r)
		}
	}()

	resp, err = handler(ctx, req)
	if err != nil {
		return resp, err
	}

	//var validatorCfg middleware.ValidatorConfig
	//_ = config.ScanKey("validator", &validatorCfg)
	//if !validatorCfg.CheckResponse {
	//	return
	//}
	//if err = middleware.Validate(resp); err != nil {
	//	logs.Errorf("validate response failed, err: %s", err)
	//	return nil, core.NewError(http.StatusInternalServerError, err.Error())
	//}
	return
}
