// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: armory/auth/user.proto
// Protobuf Java Version: 4.33.4

package io.ncraft.armory.auth;

/**
 * Protobuf type {@code armory.auth.User}
 */
@com.google.protobuf.Generated
public final class User extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:armory.auth.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "User");
  }
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private User() {
    id_ = "";
    name_ = "";
    description_ = "";
    domain_ = "";
    password_ = "";
    salt_ = "";
    passwordAlgorithm_ = "";
    phoneNumber_ = "";
    emailAddress_ = "";
    nickName_ = "";
    otpSecret_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.armory.auth.UserProto.internal_static_armory_auth_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.armory.auth.UserProto.internal_static_armory_auth_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.armory.auth.User.class, io.ncraft.armory.auth.User.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOMAIN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domain_ = "";
  /**
   * <code>string domain = 4;</code>
   * @return The domain.
   */
  @java.lang.Override
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domain_ = s;
      return s;
    }
  }
  /**
   * <code>string domain = 4;</code>
   * @return The bytes for domain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object password_ = "";
  /**
   * <code>string password = 5;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 5;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object salt_ = "";
  /**
   * <code>string salt = 6;</code>
   * @return The salt.
   */
  @java.lang.Override
  public java.lang.String getSalt() {
    java.lang.Object ref = salt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      salt_ = s;
      return s;
    }
  }
  /**
   * <code>string salt = 6;</code>
   * @return The bytes for salt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSaltBytes() {
    java.lang.Object ref = salt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      salt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_ALGORITHM_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object passwordAlgorithm_ = "";
  /**
   * <code>string password_algorithm = 7;</code>
   * @return The passwordAlgorithm.
   */
  @java.lang.Override
  public java.lang.String getPasswordAlgorithm() {
    java.lang.Object ref = passwordAlgorithm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      passwordAlgorithm_ = s;
      return s;
    }
  }
  /**
   * <code>string password_algorithm = 7;</code>
   * @return The bytes for passwordAlgorithm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordAlgorithmBytes() {
    java.lang.Object ref = passwordAlgorithm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      passwordAlgorithm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_NUMBER_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object phoneNumber_ = "";
  /**
   * <code>string phone_number = 10;</code>
   * @return The phoneNumber.
   */
  @java.lang.Override
  public java.lang.String getPhoneNumber() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phoneNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string phone_number = 10;</code>
   * @return The bytes for phoneNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneNumberBytes() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phoneNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_ADDRESS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object emailAddress_ = "";
  /**
   * <code>string email_address = 11;</code>
   * @return The emailAddress.
   */
  @java.lang.Override
  public java.lang.String getEmailAddress() {
    java.lang.Object ref = emailAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      emailAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string email_address = 11;</code>
   * @return The bytes for emailAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailAddressBytes() {
    java.lang.Object ref = emailAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      emailAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICK_NAME_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nickName_ = "";
  /**
   * <code>string nick_name = 13;</code>
   * @return The nickName.
   */
  @java.lang.Override
  public java.lang.String getNickName() {
    java.lang.Object ref = nickName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nickName_ = s;
      return s;
    }
  }
  /**
   * <code>string nick_name = 13;</code>
   * @return The bytes for nickName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNickNameBytes() {
    java.lang.Object ref = nickName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVE_FIELD_NUMBER = 20;
  private boolean active_ = false;
  /**
   * <code>bool active = 20;</code>
   * @return The active.
   */
  @java.lang.Override
  public boolean getActive() {
    return active_;
  }

  public static final int OTP_SECRET_FIELD_NUMBER = 21;
  @SuppressWarnings("serial")
  private volatile java.lang.Object otpSecret_ = "";
  /**
   * <code>string otp_secret = 21;</code>
   * @return The otpSecret.
   */
  @java.lang.Override
  public java.lang.String getOtpSecret() {
    java.lang.Object ref = otpSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      otpSecret_ = s;
      return s;
    }
  }
  /**
   * <code>string otp_secret = 21;</code>
   * @return The bytes for otpSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOtpSecretBytes() {
    java.lang.Object ref = otpSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      otpSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_ADMIN_FIELD_NUMBER = 25;
  private boolean isAdmin_ = false;
  /**
   * <code>bool is_admin = 25;</code>
   * @return The isAdmin.
   */
  @java.lang.Override
  public boolean getIsAdmin() {
    return isAdmin_;
  }

  public static final int LOGIN_TIME_FIELD_NUMBER = 30;
  private org.mojolang.mojo.core.Timestamp loginTime_;
  /**
   * <code>.mojo.core.Timestamp login_time = 30;</code>
   * @return Whether the loginTime field is set.
   */
  @java.lang.Override
  public boolean hasLoginTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mojo.core.Timestamp login_time = 30;</code>
   * @return The loginTime.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Timestamp getLoginTime() {
    return loginTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : loginTime_;
  }
  /**
   * <code>.mojo.core.Timestamp login_time = 30;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.TimestampOrBuilder getLoginTimeOrBuilder() {
    return loginTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : loginTime_;
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 1000;
  private org.mojolang.mojo.core.Timestamp createTime_;
  /**
   * <code>.mojo.core.Timestamp create_time = 1000;</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.mojo.core.Timestamp create_time = 1000;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Timestamp getCreateTime() {
    return createTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <code>.mojo.core.Timestamp create_time = 1000;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATE_TIME_FIELD_NUMBER = 1001;
  private org.mojolang.mojo.core.Timestamp updateTime_;
  /**
   * <code>.mojo.core.Timestamp update_time = 1001;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.mojo.core.Timestamp update_time = 1001;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Timestamp getUpdateTime() {
    return updateTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <code>.mojo.core.Timestamp update_time = 1001;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : updateTime_;
  }

  public static final int DELETE_TIME_FIELD_NUMBER = 1002;
  private org.mojolang.mojo.db.DeleteTime deleteTime_;
  /**
   * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
   * @return Whether the deleteTime field is set.
   */
  @java.lang.Override
  public boolean hasDeleteTime() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
   * @return The deleteTime.
   */
  @java.lang.Override
  public org.mojolang.mojo.db.DeleteTime getDeleteTime() {
    return deleteTime_ == null ? org.mojolang.mojo.db.DeleteTime.getDefaultInstance() : deleteTime_;
  }
  /**
   * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.db.DeleteTimeOrBuilder getDeleteTimeOrBuilder() {
    return deleteTime_ == null ? org.mojolang.mojo.db.DeleteTime.getDefaultInstance() : deleteTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(domain_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, domain_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, password_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(salt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, salt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(passwordAlgorithm_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, passwordAlgorithm_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phoneNumber_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, phoneNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(emailAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, emailAddress_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nickName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, nickName_);
    }
    if (active_ != false) {
      output.writeBool(20, active_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(otpSecret_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 21, otpSecret_);
    }
    if (isAdmin_ != false) {
      output.writeBool(25, isAdmin_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(30, getLoginTime());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(1000, getCreateTime());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(1001, getUpdateTime());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(1002, getDeleteTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(domain_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, domain_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, password_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(salt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, salt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(passwordAlgorithm_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, passwordAlgorithm_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phoneNumber_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, phoneNumber_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(emailAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, emailAddress_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nickName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, nickName_);
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(20, active_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(otpSecret_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(21, otpSecret_);
    }
    if (isAdmin_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(25, isAdmin_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(30, getLoginTime());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1000, getCreateTime());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1001, getUpdateTime());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1002, getDeleteTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.armory.auth.User)) {
      return super.equals(obj);
    }
    io.ncraft.armory.auth.User other = (io.ncraft.armory.auth.User) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getDomain()
        .equals(other.getDomain())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getSalt()
        .equals(other.getSalt())) return false;
    if (!getPasswordAlgorithm()
        .equals(other.getPasswordAlgorithm())) return false;
    if (!getPhoneNumber()
        .equals(other.getPhoneNumber())) return false;
    if (!getEmailAddress()
        .equals(other.getEmailAddress())) return false;
    if (!getNickName()
        .equals(other.getNickName())) return false;
    if (getActive()
        != other.getActive()) return false;
    if (!getOtpSecret()
        .equals(other.getOtpSecret())) return false;
    if (getIsAdmin()
        != other.getIsAdmin()) return false;
    if (hasLoginTime() != other.hasLoginTime()) return false;
    if (hasLoginTime()) {
      if (!getLoginTime()
          .equals(other.getLoginTime())) return false;
    }
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (hasDeleteTime() != other.hasDeleteTime()) return false;
    if (hasDeleteTime()) {
      if (!getDeleteTime()
          .equals(other.getDeleteTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getDomain().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + SALT_FIELD_NUMBER;
    hash = (53 * hash) + getSalt().hashCode();
    hash = (37 * hash) + PASSWORD_ALGORITHM_FIELD_NUMBER;
    hash = (53 * hash) + getPasswordAlgorithm().hashCode();
    hash = (37 * hash) + PHONE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPhoneNumber().hashCode();
    hash = (37 * hash) + EMAIL_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getEmailAddress().hashCode();
    hash = (37 * hash) + NICK_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickName().hashCode();
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    hash = (37 * hash) + OTP_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getOtpSecret().hashCode();
    hash = (37 * hash) + IS_ADMIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAdmin());
    if (hasLoginTime()) {
      hash = (37 * hash) + LOGIN_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginTime().hashCode();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    if (hasDeleteTime()) {
      hash = (37 * hash) + DELETE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.armory.auth.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.armory.auth.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.armory.auth.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.armory.auth.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.armory.auth.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.armory.auth.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.armory.auth.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code armory.auth.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:armory.auth.User)
      io.ncraft.armory.auth.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.armory.auth.UserProto.internal_static_armory_auth_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.armory.auth.UserProto.internal_static_armory_auth_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.armory.auth.User.class, io.ncraft.armory.auth.User.Builder.class);
    }

    // Construct using io.ncraft.armory.auth.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetLoginTimeFieldBuilder();
        internalGetCreateTimeFieldBuilder();
        internalGetUpdateTimeFieldBuilder();
        internalGetDeleteTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      description_ = "";
      domain_ = "";
      password_ = "";
      salt_ = "";
      passwordAlgorithm_ = "";
      phoneNumber_ = "";
      emailAddress_ = "";
      nickName_ = "";
      active_ = false;
      otpSecret_ = "";
      isAdmin_ = false;
      loginTime_ = null;
      if (loginTimeBuilder_ != null) {
        loginTimeBuilder_.dispose();
        loginTimeBuilder_ = null;
      }
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      updateTime_ = null;
      if (updateTimeBuilder_ != null) {
        updateTimeBuilder_.dispose();
        updateTimeBuilder_ = null;
      }
      deleteTime_ = null;
      if (deleteTimeBuilder_ != null) {
        deleteTimeBuilder_.dispose();
        deleteTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.armory.auth.UserProto.internal_static_armory_auth_User_descriptor;
    }

    @java.lang.Override
    public io.ncraft.armory.auth.User getDefaultInstanceForType() {
      return io.ncraft.armory.auth.User.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.armory.auth.User build() {
      io.ncraft.armory.auth.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.armory.auth.User buildPartial() {
      io.ncraft.armory.auth.User result = new io.ncraft.armory.auth.User(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.ncraft.armory.auth.User result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.domain_ = domain_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.password_ = password_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.salt_ = salt_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.passwordAlgorithm_ = passwordAlgorithm_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.phoneNumber_ = phoneNumber_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.emailAddress_ = emailAddress_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.nickName_ = nickName_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.active_ = active_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.otpSecret_ = otpSecret_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.isAdmin_ = isAdmin_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.loginTime_ = loginTimeBuilder_ == null
            ? loginTime_
            : loginTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.createTime_ = createTimeBuilder_ == null
            ? createTime_
            : createTimeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.updateTime_ = updateTimeBuilder_ == null
            ? updateTime_
            : updateTimeBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.deleteTime_ = deleteTimeBuilder_ == null
            ? deleteTime_
            : deleteTimeBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.armory.auth.User) {
        return mergeFrom((io.ncraft.armory.auth.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.armory.auth.User other) {
      if (other == io.ncraft.armory.auth.User.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDomain().isEmpty()) {
        domain_ = other.domain_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSalt().isEmpty()) {
        salt_ = other.salt_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getPasswordAlgorithm().isEmpty()) {
        passwordAlgorithm_ = other.passwordAlgorithm_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getPhoneNumber().isEmpty()) {
        phoneNumber_ = other.phoneNumber_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getEmailAddress().isEmpty()) {
        emailAddress_ = other.emailAddress_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getNickName().isEmpty()) {
        nickName_ = other.nickName_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (!other.getOtpSecret().isEmpty()) {
        otpSecret_ = other.otpSecret_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (other.getIsAdmin() != false) {
        setIsAdmin(other.getIsAdmin());
      }
      if (other.hasLoginTime()) {
        mergeLoginTime(other.getLoginTime());
      }
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      if (other.hasDeleteTime()) {
        mergeDeleteTime(other.getDeleteTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              domain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              password_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              salt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              passwordAlgorithm_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 82: {
              phoneNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 82
            case 90: {
              emailAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 90
            case 106: {
              nickName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 106
            case 160: {
              active_ = input.readBool();
              bitField0_ |= 0x00000400;
              break;
            } // case 160
            case 170: {
              otpSecret_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 170
            case 200: {
              isAdmin_ = input.readBool();
              bitField0_ |= 0x00001000;
              break;
            } // case 200
            case 242: {
              input.readMessage(
                  internalGetLoginTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00002000;
              break;
            } // case 242
            case 8002: {
              input.readMessage(
                  internalGetCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00004000;
              break;
            } // case 8002
            case 8010: {
              input.readMessage(
                  internalGetUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00008000;
              break;
            } // case 8010
            case 8018: {
              input.readMessage(
                  internalGetDeleteTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00010000;
              break;
            } // case 8018
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object domain_ = "";
    /**
     * <code>string domain = 4;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string domain = 4;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string domain = 4;</code>
     * @param value The domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domain_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomain() {
      domain_ = getDefaultInstance().getDomain();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string domain = 4;</code>
     * @param value The bytes for domain to set.
     * @return This builder for chaining.
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domain_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 5;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 5;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 5;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      password_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      password_ = getDefaultInstance().getPassword();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string password = 5;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      password_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object salt_ = "";
    /**
     * <code>string salt = 6;</code>
     * @return The salt.
     */
    public java.lang.String getSalt() {
      java.lang.Object ref = salt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string salt = 6;</code>
     * @return The bytes for salt.
     */
    public com.google.protobuf.ByteString
        getSaltBytes() {
      java.lang.Object ref = salt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salt = 6;</code>
     * @param value The salt to set.
     * @return This builder for chaining.
     */
    public Builder setSalt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      salt_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string salt = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalt() {
      salt_ = getDefaultInstance().getSalt();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string salt = 6;</code>
     * @param value The bytes for salt to set.
     * @return This builder for chaining.
     */
    public Builder setSaltBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      salt_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object passwordAlgorithm_ = "";
    /**
     * <code>string password_algorithm = 7;</code>
     * @return The passwordAlgorithm.
     */
    public java.lang.String getPasswordAlgorithm() {
      java.lang.Object ref = passwordAlgorithm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passwordAlgorithm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password_algorithm = 7;</code>
     * @return The bytes for passwordAlgorithm.
     */
    public com.google.protobuf.ByteString
        getPasswordAlgorithmBytes() {
      java.lang.Object ref = passwordAlgorithm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwordAlgorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password_algorithm = 7;</code>
     * @param value The passwordAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordAlgorithm(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      passwordAlgorithm_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string password_algorithm = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPasswordAlgorithm() {
      passwordAlgorithm_ = getDefaultInstance().getPasswordAlgorithm();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string password_algorithm = 7;</code>
     * @param value The bytes for passwordAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordAlgorithmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      passwordAlgorithm_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object phoneNumber_ = "";
    /**
     * <code>string phone_number = 10;</code>
     * @return The phoneNumber.
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phone_number = 10;</code>
     * @return The bytes for phoneNumber.
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phone_number = 10;</code>
     * @param value The phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      phoneNumber_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string phone_number = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNumber() {
      phoneNumber_ = getDefaultInstance().getPhoneNumber();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string phone_number = 10;</code>
     * @param value The bytes for phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      phoneNumber_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object emailAddress_ = "";
    /**
     * <code>string email_address = 11;</code>
     * @return The emailAddress.
     */
    public java.lang.String getEmailAddress() {
      java.lang.Object ref = emailAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email_address = 11;</code>
     * @return The bytes for emailAddress.
     */
    public com.google.protobuf.ByteString
        getEmailAddressBytes() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email_address = 11;</code>
     * @param value The emailAddress to set.
     * @return This builder for chaining.
     */
    public Builder setEmailAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      emailAddress_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string email_address = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmailAddress() {
      emailAddress_ = getDefaultInstance().getEmailAddress();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string email_address = 11;</code>
     * @param value The bytes for emailAddress to set.
     * @return This builder for chaining.
     */
    public Builder setEmailAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      emailAddress_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object nickName_ = "";
    /**
     * <code>string nick_name = 13;</code>
     * @return The nickName.
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nick_name = 13;</code>
     * @return The bytes for nickName.
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nick_name = 13;</code>
     * @param value The nickName to set.
     * @return This builder for chaining.
     */
    public Builder setNickName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nickName_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string nick_name = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearNickName() {
      nickName_ = getDefaultInstance().getNickName();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string nick_name = 13;</code>
     * @param value The bytes for nickName to set.
     * @return This builder for chaining.
     */
    public Builder setNickNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nickName_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 20;</code>
     * @return The active.
     */
    @java.lang.Override
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 20;</code>
     * @param value The active to set.
     * @return This builder for chaining.
     */
    public Builder setActive(boolean value) {

      active_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00000400);
      active_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object otpSecret_ = "";
    /**
     * <code>string otp_secret = 21;</code>
     * @return The otpSecret.
     */
    public java.lang.String getOtpSecret() {
      java.lang.Object ref = otpSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otpSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string otp_secret = 21;</code>
     * @return The bytes for otpSecret.
     */
    public com.google.protobuf.ByteString
        getOtpSecretBytes() {
      java.lang.Object ref = otpSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otpSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string otp_secret = 21;</code>
     * @param value The otpSecret to set.
     * @return This builder for chaining.
     */
    public Builder setOtpSecret(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      otpSecret_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string otp_secret = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearOtpSecret() {
      otpSecret_ = getDefaultInstance().getOtpSecret();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string otp_secret = 21;</code>
     * @param value The bytes for otpSecret to set.
     * @return This builder for chaining.
     */
    public Builder setOtpSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      otpSecret_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private boolean isAdmin_ ;
    /**
     * <code>bool is_admin = 25;</code>
     * @return The isAdmin.
     */
    @java.lang.Override
    public boolean getIsAdmin() {
      return isAdmin_;
    }
    /**
     * <code>bool is_admin = 25;</code>
     * @param value The isAdmin to set.
     * @return This builder for chaining.
     */
    public Builder setIsAdmin(boolean value) {

      isAdmin_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_admin = 25;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsAdmin() {
      bitField0_ = (bitField0_ & ~0x00001000);
      isAdmin_ = false;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Timestamp loginTime_;
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> loginTimeBuilder_;
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     * @return Whether the loginTime field is set.
     */
    public boolean hasLoginTime() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     * @return The loginTime.
     */
    public org.mojolang.mojo.core.Timestamp getLoginTime() {
      if (loginTimeBuilder_ == null) {
        return loginTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : loginTime_;
      } else {
        return loginTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    public Builder setLoginTime(org.mojolang.mojo.core.Timestamp value) {
      if (loginTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginTime_ = value;
      } else {
        loginTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    public Builder setLoginTime(
        org.mojolang.mojo.core.Timestamp.Builder builderForValue) {
      if (loginTimeBuilder_ == null) {
        loginTime_ = builderForValue.build();
      } else {
        loginTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    public Builder mergeLoginTime(org.mojolang.mojo.core.Timestamp value) {
      if (loginTimeBuilder_ == null) {
        if (((bitField0_ & 0x00002000) != 0) &&
          loginTime_ != null &&
          loginTime_ != org.mojolang.mojo.core.Timestamp.getDefaultInstance()) {
          getLoginTimeBuilder().mergeFrom(value);
        } else {
          loginTime_ = value;
        }
      } else {
        loginTimeBuilder_.mergeFrom(value);
      }
      if (loginTime_ != null) {
        bitField0_ |= 0x00002000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    public Builder clearLoginTime() {
      bitField0_ = (bitField0_ & ~0x00002000);
      loginTime_ = null;
      if (loginTimeBuilder_ != null) {
        loginTimeBuilder_.dispose();
        loginTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    public org.mojolang.mojo.core.Timestamp.Builder getLoginTimeBuilder() {
      bitField0_ |= 0x00002000;
      onChanged();
      return internalGetLoginTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    public org.mojolang.mojo.core.TimestampOrBuilder getLoginTimeOrBuilder() {
      if (loginTimeBuilder_ != null) {
        return loginTimeBuilder_.getMessageOrBuilder();
      } else {
        return loginTime_ == null ?
            org.mojolang.mojo.core.Timestamp.getDefaultInstance() : loginTime_;
      }
    }
    /**
     * <code>.mojo.core.Timestamp login_time = 30;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> 
        internalGetLoginTimeFieldBuilder() {
      if (loginTimeBuilder_ == null) {
        loginTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder>(
                getLoginTime(),
                getParentForChildren(),
                isClean());
        loginTime_ = null;
      }
      return loginTimeBuilder_;
    }

    private org.mojolang.mojo.core.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     * @return The createTime.
     */
    public org.mojolang.mojo.core.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    public Builder setCreateTime(org.mojolang.mojo.core.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    public Builder setCreateTime(
        org.mojolang.mojo.core.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    public Builder mergeCreateTime(org.mojolang.mojo.core.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00004000) != 0) &&
          createTime_ != null &&
          createTime_ != org.mojolang.mojo.core.Timestamp.getDefaultInstance()) {
          getCreateTimeBuilder().mergeFrom(value);
        } else {
          createTime_ = value;
        }
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      if (createTime_ != null) {
        bitField0_ |= 0x00004000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00004000);
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    public org.mojolang.mojo.core.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00004000;
      onChanged();
      return internalGetCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    public org.mojolang.mojo.core.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            org.mojolang.mojo.core.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <code>.mojo.core.Timestamp create_time = 1000;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> 
        internalGetCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private org.mojolang.mojo.core.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     * @return The updateTime.
     */
    public org.mojolang.mojo.core.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    public Builder setUpdateTime(org.mojolang.mojo.core.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    public Builder setUpdateTime(
        org.mojolang.mojo.core.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    public Builder mergeUpdateTime(org.mojolang.mojo.core.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00008000) != 0) &&
          updateTime_ != null &&
          updateTime_ != org.mojolang.mojo.core.Timestamp.getDefaultInstance()) {
          getUpdateTimeBuilder().mergeFrom(value);
        } else {
          updateTime_ = value;
        }
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      if (updateTime_ != null) {
        bitField0_ |= 0x00008000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    public Builder clearUpdateTime() {
      bitField0_ = (bitField0_ & ~0x00008000);
      updateTime_ = null;
      if (updateTimeBuilder_ != null) {
        updateTimeBuilder_.dispose();
        updateTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    public org.mojolang.mojo.core.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00008000;
      onChanged();
      return internalGetUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    public org.mojolang.mojo.core.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            org.mojolang.mojo.core.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <code>.mojo.core.Timestamp update_time = 1001;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> 
        internalGetUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }

    private org.mojolang.mojo.db.DeleteTime deleteTime_;
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.db.DeleteTime, org.mojolang.mojo.db.DeleteTime.Builder, org.mojolang.mojo.db.DeleteTimeOrBuilder> deleteTimeBuilder_;
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     * @return Whether the deleteTime field is set.
     */
    public boolean hasDeleteTime() {
      return ((bitField0_ & 0x00010000) != 0);
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     * @return The deleteTime.
     */
    public org.mojolang.mojo.db.DeleteTime getDeleteTime() {
      if (deleteTimeBuilder_ == null) {
        return deleteTime_ == null ? org.mojolang.mojo.db.DeleteTime.getDefaultInstance() : deleteTime_;
      } else {
        return deleteTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    public Builder setDeleteTime(org.mojolang.mojo.db.DeleteTime value) {
      if (deleteTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deleteTime_ = value;
      } else {
        deleteTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    public Builder setDeleteTime(
        org.mojolang.mojo.db.DeleteTime.Builder builderForValue) {
      if (deleteTimeBuilder_ == null) {
        deleteTime_ = builderForValue.build();
      } else {
        deleteTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    public Builder mergeDeleteTime(org.mojolang.mojo.db.DeleteTime value) {
      if (deleteTimeBuilder_ == null) {
        if (((bitField0_ & 0x00010000) != 0) &&
          deleteTime_ != null &&
          deleteTime_ != org.mojolang.mojo.db.DeleteTime.getDefaultInstance()) {
          getDeleteTimeBuilder().mergeFrom(value);
        } else {
          deleteTime_ = value;
        }
      } else {
        deleteTimeBuilder_.mergeFrom(value);
      }
      if (deleteTime_ != null) {
        bitField0_ |= 0x00010000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    public Builder clearDeleteTime() {
      bitField0_ = (bitField0_ & ~0x00010000);
      deleteTime_ = null;
      if (deleteTimeBuilder_ != null) {
        deleteTimeBuilder_.dispose();
        deleteTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    public org.mojolang.mojo.db.DeleteTime.Builder getDeleteTimeBuilder() {
      bitField0_ |= 0x00010000;
      onChanged();
      return internalGetDeleteTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    public org.mojolang.mojo.db.DeleteTimeOrBuilder getDeleteTimeOrBuilder() {
      if (deleteTimeBuilder_ != null) {
        return deleteTimeBuilder_.getMessageOrBuilder();
      } else {
        return deleteTime_ == null ?
            org.mojolang.mojo.db.DeleteTime.getDefaultInstance() : deleteTime_;
      }
    }
    /**
     * <code>.mojo.db.DeleteTime delete_time = 1002;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.db.DeleteTime, org.mojolang.mojo.db.DeleteTime.Builder, org.mojolang.mojo.db.DeleteTimeOrBuilder> 
        internalGetDeleteTimeFieldBuilder() {
      if (deleteTimeBuilder_ == null) {
        deleteTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.mojolang.mojo.db.DeleteTime, org.mojolang.mojo.db.DeleteTime.Builder, org.mojolang.mojo.db.DeleteTimeOrBuilder>(
                getDeleteTime(),
                getParentForChildren(),
                isClean());
        deleteTime_ = null;
      }
      return deleteTimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:armory.auth.User)
  }

  // @@protoc_insertion_point(class_scope:armory.auth.User)
  private static final io.ncraft.armory.auth.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.armory.auth.User();
  }

  public static io.ncraft.armory.auth.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.armory.auth.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

