// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package unitable

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/mojo-lang/core/go/pkg/mojo/core"
)

func init() {
	core.RegisterJSONTypeDecoder("unitable.ListRowStatResponse", &ListRowStatResponseCodec{})
	core.RegisterJSONTypeEncoder("unitable.ListRowStatResponse", &ListRowStatResponseCodec{})
}

type ListRowStatResponseCodec struct {
}

func (codec *ListRowStatResponseCodec) Decode(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	any := iter.ReadAny()
	listRowStatResponse := (*ListRowStatResponse)(ptr)
	if any.ValueType() == jsoniter.ArrayValue {
		any.ToVal(&listRowStatResponse.Objects)
	}
}

func (codec *ListRowStatResponseCodec) IsEmpty(ptr unsafe.Pointer) bool {
	listRowStatResponse := (*ListRowStatResponse)(ptr)
	return listRowStatResponse == nil || len(listRowStatResponse.Objects) == 0
}

func (codec *ListRowStatResponseCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	listRowStatResponse := (*ListRowStatResponse)(ptr)
	if len(listRowStatResponse.Objects) > 0 {
		stream.WriteVal(listRowStatResponse.Objects)
	} else {
		stream.WriteRaw("[]")
	}
}
