// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package unitable

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/mojo-lang/mojo/go/pkg/mojo/core"
)

func init() {
	core.RegisterJSONTypeDecoder("unitable.ListDbQueriesResponse", &ListDbQueriesResponseCodec{})
	core.RegisterJSONTypeEncoder("unitable.ListDbQueriesResponse", &ListDbQueriesResponseCodec{})
}

type ListDbQueriesResponseCodec struct {
}

func (codec *ListDbQueriesResponseCodec) Decode(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	any := iter.ReadAny()
	listDbQueriesResponse := (*ListDbQueriesResponse)(ptr)
	if any.ValueType() == jsoniter.ArrayValue {
		any.ToVal(&listDbQueriesResponse.DbQueries)
	}
}

func (codec *ListDbQueriesResponseCodec) IsEmpty(ptr unsafe.Pointer) bool {
	listDbQueriesResponse := (*ListDbQueriesResponse)(ptr)
	return listDbQueriesResponse == nil || len(listDbQueriesResponse.DbQueries) == 0
}

func (codec *ListDbQueriesResponseCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	listDbQueriesResponse := (*ListDbQueriesResponse)(ptr)
	if len(listDbQueriesResponse.DbQueries) > 0 {
		stream.WriteVal(listDbQueriesResponse.DbQueries)
	} else {
		stream.WriteRaw("[]")
	}
}
