// Code generated by mojo. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"sync"

	"github.com/mojo-lang/mojo/go/pkg/mojo/db"
	"github.com/mojo-lang/mojo/go/pkg/mojo/db/query"
	entity "github.com/ncraft-io/armory/go/pkg/armory/auth"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var policyInstance *Policy
var policyInstanceOnce sync.Once

func GetPolicyModel() *Policy {
	var err error
	policyInstanceOnce.Do(func() {
		policyInstance, err = NewPolicy(GetDB())
		if err != nil {
			panic(fmt.Sprintf("failed to create Policy module %v", err))
		}
	})

	return policyInstance
}

type Policy struct {
	DB        *db.DB
	keyColumn string
}

// NewPolicy uses the service's database connection. Migration is controlled
// by db.Config.DisableAutoMigrate; connection ownership stays with the caller.
func NewPolicy(database *db.DB) (*Policy, error) {
	column, err := prepareModel(database, &entity.Policy{}, "Id")
	if err != nil {
		return nil, err
	}
	return &Policy{DB: database, keyColumn: column}, nil
}

func (m *Policy) Create(ctx context.Context, value *entity.Policy) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("Policy: nil record")
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(value)
	return result.RowsAffected, result.Error
}

func (m *Policy) Get(ctx context.Context, id string) (*entity.Policy, error) {
	value := &entity.Policy{}
	err := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).First(value).Error
	if err != nil {
		return nil, err
	}
	return value, nil
}

func (m *Policy) Delete(ctx context.Context, id string) (int64, error) {
	result := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).Delete(&entity.Policy{})
	return result.RowsAffected, result.Error
}

// Update writes non-key fields, not including zero values, without inserting
// a missing record or changing its primary key.
func (m *Policy) Update(ctx context.Context, value *entity.Policy, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, m.keyColumn, value.Id, columns...)
}

func (m *Policy) UpdateBy(ctx context.Context, value *entity.Policy, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, keyColumn, keyValue, columns...)
}

func (m *Policy) update(tx *gorm.DB, value *entity.Policy, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("Policy: nil record")
	}
	result := tx.Model(&entity.Policy{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue})

	if len(columns) == 0 {
		result = result.Omit(keyColumn).Updates(value)
	} else {
		result = result.Select(columns).Omit(keyColumn).Updates(value)
	}

	return result.RowsAffected, result.Error
}

// Update writes all non-key fields, including zero values, without inserting
// a missing record or changing its primary key.
func (m *Policy) UpdateAll(ctx context.Context, value *entity.Policy) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, m.keyColumn, value.Id)
}

func (m *Policy) UpdateAllBy(ctx context.Context, value *entity.Policy, keyColumn string, keyValue interface{}) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, keyColumn, keyValue)
}

func (m *Policy) updateAll(tx *gorm.DB, value *entity.Policy, keyColumn string, keyValue interface{}) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("Policy: nil record")
	}
	result := tx.Model(&entity.Policy{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue}).
		Select("*").Omit(keyColumn).Updates(value)
	return result.RowsAffected, result.Error
}

func (m *Policy) List(ctx context.Context, q *query.Query) ([]*entity.Policy, error) {
	values := make([]*entity.Policy, 0)
	tx := m.DB.WithContext(ctx).Model(&entity.Policy{})
	if q != nil {
		if err := q.Normalize(); err != nil {
			return nil, err
		}
		tx = q.Apply(tx, query.Fields{
			"id": {Type: query.FieldTypeString, Repeated: false}, "name": {Type: query.FieldTypeString, Repeated: false}, "description": {Type: query.FieldTypeString, Repeated: false}, "domain": {Type: query.FieldTypeString, Repeated: false}, "effect": {Type: query.FieldTypeJSON, Repeated: false}, "subjects": {Type: query.FieldTypeJSON, Repeated: true}, "permissions": {Type: query.FieldTypeJSON, Repeated: true}, "conditions": {Type: query.FieldTypeJSON, Repeated: true}, "create_time": {Type: query.FieldTypeDatetime, Repeated: false}, "update_time": {Type: query.FieldTypeDatetime, Repeated: false},
		})
	}
	if err := tx.Find(&values).Error; err != nil {
		return nil, err
	}
	return values, nil
}

func (m *Policy) BatchCreate(ctx context.Context, values ...*entity.Policy) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	for _, value := range values {
		if value == nil {
			return 0, fmt.Errorf("Policy: nil record")
		}
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(values, len(values))
	return result.RowsAffected, result.Error
}

func (m *Policy) BatchGet(ctx context.Context, ids ...string) ([]*entity.Policy, error) {
	values := make([]*entity.Policy, 0)
	if len(ids) == 0 {
		return values, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	err := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Find(&values).Error
	if err != nil {
		return nil, err
	}
	return values, nil
}

func (m *Policy) BatchDelete(ctx context.Context, ids ...string) (int64, error) {
	if len(ids) == 0 {
		return 0, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	result := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Delete(&entity.Policy{})
	return result.RowsAffected, result.Error
}

func (m *Policy) BatchUpdate(ctx context.Context, values []*entity.Policy, columns ...string) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.update(tx, value, m.keyColumn, value.Id, columns...)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}

func (m *Policy) BatchUpdateAll(ctx context.Context, values []*entity.Policy) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.updateAll(tx, value, m.keyColumn, value.Id)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}
