// Code generated by mojo. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"sync"

	"github.com/mojo-lang/mojo/go/pkg/mojo/db"
	"github.com/mojo-lang/mojo/go/pkg/mojo/db/query"
	entity "github.com/ncraft-io/armory/go/pkg/armory/unitable"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var tableInstance *Table
var tableInstanceOnce sync.Once

func GetTableModel() *Table {
	var err error
	tableInstanceOnce.Do(func() {
		tableInstance, err = NewTable(GetDB())
		if err != nil {
			panic(fmt.Sprintf("failed to create Table module %v", err))
		}
	})

	return tableInstance
}

type Table struct {
	DB        *db.DB
	keyColumn string
}

// NewTable uses the service's database connection. Migration is controlled
// by db.Config.DisableAutoMigrate; connection ownership stays with the caller.
func NewTable(database *db.DB) (*Table, error) {
	column, err := prepareModel(database, &entity.Table{}, "Id")
	if err != nil {
		return nil, err
	}
	return &Table{DB: database, keyColumn: column}, nil
}

func (m *Table) Create(ctx context.Context, value *entity.Table) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("Table: nil record")
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(value)
	return result.RowsAffected, result.Error
}

func (m *Table) Get(ctx context.Context, id string) (*entity.Table, error) {
	value := &entity.Table{}
	err := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).First(value).Error
	if err != nil {
		return nil, err
	}
	return value, nil
}

func (m *Table) Delete(ctx context.Context, id string) (int64, error) {
	result := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).Delete(&entity.Table{})
	return result.RowsAffected, result.Error
}

// Update writes non-key fields, not including zero values, without inserting
// a missing record or changing its primary key.
func (m *Table) Update(ctx context.Context, value *entity.Table, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, m.keyColumn, value.Id, columns...)
}

func (m *Table) UpdateBy(ctx context.Context, value *entity.Table, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, keyColumn, keyValue, columns...)
}

func (m *Table) update(tx *gorm.DB, value *entity.Table, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("Table: nil record")
	}
	result := tx.Model(&entity.Table{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue})

	if len(columns) == 0 {
		result = result.Omit(keyColumn).Updates(value)
	} else {
		result = result.Select(columns).Omit(keyColumn).Updates(value)
	}

	return result.RowsAffected, result.Error
}

// Update writes all non-key fields, including zero values, without inserting
// a missing record or changing its primary key.
func (m *Table) UpdateAll(ctx context.Context, value *entity.Table) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, m.keyColumn, value.Id)
}

func (m *Table) UpdateAllBy(ctx context.Context, value *entity.Table, keyColumn string, keyValue interface{}) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, keyColumn, keyValue)
}

func (m *Table) updateAll(tx *gorm.DB, value *entity.Table, keyColumn string, keyValue interface{}) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("Table: nil record")
	}
	result := tx.Model(&entity.Table{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue}).
		Select("*").Omit(keyColumn).Updates(value)
	return result.RowsAffected, result.Error
}

func (m *Table) List(ctx context.Context, q *query.Query) ([]*entity.Table, error) {
	values := make([]*entity.Table, 0)
	tx := m.DB.WithContext(ctx).Model(&entity.Table{})
	if q != nil {
		if err := q.Normalize(); err != nil {
			return nil, err
		}
		tx = q.Apply(tx, query.Fields{
			"id": {Type: query.FieldTypeString, Repeated: false}, "name": {Type: query.FieldTypeString, Repeated: false}, "display_name": {Type: query.FieldTypeString, Repeated: false}, "export_name": {Type: query.FieldTypeString, Repeated: false}, "tenant": {Type: query.FieldTypeString, Repeated: false}, "database": {Type: query.FieldTypeString, Repeated: false}, "json_style": {Type: query.FieldTypeString, Repeated: false}, "columns": {Type: query.FieldTypeJSON, Repeated: true}, "create_time": {Type: query.FieldTypeDatetime, Repeated: false}, "update_time": {Type: query.FieldTypeDatetime, Repeated: false},
		})
	}
	if err := tx.Find(&values).Error; err != nil {
		return nil, err
	}
	return values, nil
}

func (m *Table) BatchCreate(ctx context.Context, values ...*entity.Table) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	for _, value := range values {
		if value == nil {
			return 0, fmt.Errorf("Table: nil record")
		}
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(values, len(values))
	return result.RowsAffected, result.Error
}

func (m *Table) BatchGet(ctx context.Context, ids ...string) ([]*entity.Table, error) {
	values := make([]*entity.Table, 0)
	if len(ids) == 0 {
		return values, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	err := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Find(&values).Error
	if err != nil {
		return nil, err
	}
	return values, nil
}

func (m *Table) BatchDelete(ctx context.Context, ids ...string) (int64, error) {
	if len(ids) == 0 {
		return 0, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	result := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Delete(&entity.Table{})
	return result.RowsAffected, result.Error
}

func (m *Table) BatchUpdate(ctx context.Context, values []*entity.Table, columns ...string) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.update(tx, value, m.keyColumn, value.Id, columns...)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}

func (m *Table) BatchUpdateAll(ctx context.Context, values []*entity.Table) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.updateAll(tx, value, m.keyColumn, value.Id)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}
