// Code generated by ncraft. DO NOT EDIT.
// Rerunning ncraft will overwrite this file.
// Version: 0.1.0
// Version Date:

package svc

// This file provides server-side bindings for the HTTP transport.
// It utilizes the transport/http.Server.

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"reflect"
	"strconv"
	"strings"

	"context"

	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/tracing/opentracing"
	"github.com/gorilla/mux"
	"github.com/json-iterator/go"
	"github.com/ncraft-io/ncraft/go/pkg/ncraft/logs"
	"github.com/pkg/errors"

	httptransport "github.com/go-kit/kit/transport/http"
	mjhttp "github.com/mojo-lang/mojo/go/pkg/mojo/http"
	pagination "github.com/ncraft-io/ncraft/go/pkg/gokit/pagination"
	nhttp "github.com/ncraft-io/ncraft/go/pkg/gokit/transport/http"
	stdopentracing "github.com/opentracing/opentracing-go"

	"github.com/mojo-lang/mojo/go/pkg/mojo/core"

	"github.com/ncraft-io/armory/go/pkg/armory/file"

	// this service api
	pb "github.com/ncraft-io/armory/go/pkg/armory/file/v1"
)

const contentType = "application/json; charset=utf-8"

var (
	_ = fmt.Sprint
	_ = bytes.Compare
	_ = strconv.Atoi
	_ = httptransport.NewServer
	_ = ioutil.NopCloser
	_ = pb.NewFileClient
	_ = io.Copy
	_ = errors.Wrap
	_ = mjhttp.UnmarshalQueryParam
)

var (
	_ = file.BinaryFile{}
)

var cfg *nhttp.Config

func init() {
	cfg = nhttp.NewConfig()
}

// RegisterHttpHandler register a set of endpoints available on predefined paths to the router.
func RegisterHttpHandler(router *mux.Router, endpoints Endpoints, tracer stdopentracing.Tracer, logger log.Logger) {
	serverOptions := []httptransport.ServerOption{
		httptransport.ServerBefore(nhttp.RequestToContext, headersToContext, queryToContext),
		httptransport.ServerErrorEncoder(errorEncoder),
		httptransport.ServerErrorLogger(logger),
		httptransport.ServerAfter(httptransport.SetContentType(contentType)),
	}

	addTracerOption := func(methodName string) []httptransport.ServerOption {
		if tracer != nil {
			return append(serverOptions, httptransport.ServerBefore(opentracing.HTTPToContext(tracer, methodName, logger)))
		}
		return serverOptions
	}

	router.Methods("GET").Path("/armory/file/v1/files/{name}").Handler(
		httptransport.NewServer(
			endpoints.GetFileEndpoint,
			DecodeHTTPGetFileZeroRequest,
			EncodeHTTPGenericResponse,
			addTracerOption("get_file")...,
		//append(serverOptions, httptransport.ServerBefore(opentracing.HTTPToContext(tracer, "get_file", logger)))...,
		))
	router.Methods("HEAD").Path("/armory/file/v1/files/{name}").Handler(
		httptransport.NewServer(
			endpoints.GetFileEndpoint,
			DecodeHTTPGetFileOneRequest,
			EncodeHTTPGenericResponse,
			addTracerOption("get_file")...,
		//append(serverOptions, httptransport.ServerBefore(opentracing.HTTPToContext(tracer, "get_file", logger)))...,
		))

	router.Methods("POST").Path("/armory/file/v1/files").Handler(
		httptransport.NewServer(
			endpoints.CreateFileEndpoint,
			DecodeHTTPCreateFileZeroRequest,
			EncodeHTTPGenericResponse,
			addTracerOption("create_file")...,
		//append(serverOptions, httptransport.ServerBefore(opentracing.HTTPToContext(tracer, "create_file", logger)))...,
		))

	router.Methods("POST").Path("/armory/file/v1/files:batch").Handler(
		httptransport.NewServer(
			endpoints.BatchCreateFileEndpoint,
			DecodeHTTPBatchCreateFileZeroRequest,
			EncodeHTTPGenericResponse,
			addTracerOption("batch_create_file")...,
		//append(serverOptions, httptransport.ServerBefore(opentracing.HTTPToContext(tracer, "batch_create_file", logger)))...,
		))
}

// ErrorEncoder writes the error to the ResponseWriter, by default a content
// type of application/json, a body of json with key "error" and the value
// error.Error(), and a status code of 500. If the error implements Headerer,
// the provided headers will be applied to the response. If the error
// implements json.Marshaler, and the marshaling succeeds, the JSON encoded
// form of the error will be used. If the error implements StatusCoder, the
// provided StatusCode will be used instead of 500.
func errorEncoder(ctx context.Context, err error, w http.ResponseWriter) {
	var e *core.Error
	if core.IsError(err) {
		if ce, ok := err.(*core.Error); ok {
			e = ce
		} else if ce, ok = errors.Unwrap(err).(*core.Error); ok {
			e = ce
		}
	}
	if e == nil {
		e = core.NewErrorFrom(500, "%s", err.Error())
	}

	w.Header().Set("Content-Type", contentType)
	if headerer, ok := err.(httptransport.Headerer); ok {
		for k := range headerer.Headers() {
			w.Header().Set(k, headerer.Headers().Get(k))
		}
	}

	var body []byte
	code := http.StatusInternalServerError

	if enveloped := nhttp.IsEnvelopeStyle(ctx, cfg.GetStyle()); enveloped {
		envelope := &nhttp.EnvelopedResponse{}
		envelope.Error = e

		if cfg.GetEnvelop().MappingCode {
			if sc, ok := err.(httptransport.StatusCoder); ok {
				code = sc.StatusCode()
			}
		} else {
			code = http.StatusOK
		}

		var response interface{}
		if cfg.GetEnvelop().ErrorWrapped {
			response = envelope.ToErrorWrapped()
		} else {
			response = envelope
		}

		jsonBody, marshalErr := jsoniter.ConfigFastest.Marshal(response)
		if marshalErr != nil {
			logs.Warnw("failed to marshal the error response to json", "error", marshalErr)
		} else {
			body = jsonBody
		}
	} else {
		if sc, ok := err.(httptransport.StatusCoder); ok {
			code = sc.StatusCode()
		}
		if marshaler, ok := err.(json.Marshaler); ok {
			if jsonBody, marshalErr := marshaler.MarshalJSON(); marshalErr == nil {
				body = jsonBody
			}
		}

		if jsonBody, marshalErr := jsoniter.ConfigFastest.Marshal(e); marshalErr == nil {
			body = jsonBody
		}
	}

	w.WriteHeader(code)
	w.Write(body)
}

// Server Decode

// DecodeHTTPGetFileZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded get_file request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPGetFileZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	var req pb.GetFileRequest

	ri := interface{}(&req)
	if decoder, ok := ri.(nhttp.RequestDecoder); ok {
		if err := decoder.DecodeHttpRequest(r); err != nil {
			return nil, nhttp.WrapError(err, 400, fmt.Sprintf("cannot decode the request to GetFileRequest by customized RequestDecoder, err:%s", err.Error()))
		}
		return &req, nil
	}

	// to support gzip input
	var reader io.ReadCloser
	var err error
	switch r.Header.Get("Content-Encoding") {
	case "gzip":
		reader, err = gzip.NewReader(r.Body)
		defer reader.Close()
		if err != nil {
			return nil, nhttp.WrapError(err, 400, "failed to read the gzip content")
		}
	default:
		reader = r.Body
	}

	buf, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, nhttp.WrapError(err, 400, "cannot read body of http request")
	}
	if len(buf) > 0 {
		if err = jsoniter.ConfigFastest.Unmarshal(buf, &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, nhttp.WrapError(err,
				http.StatusBadRequest,
				fmt.Sprintf("request body '%s': cannot parse non-json request body", buf),
			)
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := core.NewUrlQueryFrom(r.URL.Query())
	_ = queryParams

	parsedQueryParams := make(map[string]bool)
	_ = parsedQueryParams

	err = mjhttp.UnmarshalPathParam(pathParams, &req.Name, "name")
	if err != nil && !core.IsNotFoundError(err) {
		return nil, nhttp.WrapError(err, 400, "cannot unmarshal the name  query parameter")
	}

	return &req, nil
}

// DecodeHTTPGetFileOneRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded get_file request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPGetFileOneRequest(_ context.Context, r *http.Request) (interface{}, error) {
	var req pb.GetFileRequest

	ri := interface{}(&req)
	if decoder, ok := ri.(nhttp.RequestDecoder); ok {
		if err := decoder.DecodeHttpRequest(r); err != nil {
			return nil, nhttp.WrapError(err, 400, fmt.Sprintf("cannot decode the request to GetFileRequest by customized RequestDecoder, err:%s", err.Error()))
		}
		return &req, nil
	}

	// to support gzip input
	var reader io.ReadCloser
	var err error
	switch r.Header.Get("Content-Encoding") {
	case "gzip":
		reader, err = gzip.NewReader(r.Body)
		defer reader.Close()
		if err != nil {
			return nil, nhttp.WrapError(err, 400, "failed to read the gzip content")
		}
	default:
		reader = r.Body
	}

	buf, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, nhttp.WrapError(err, 400, "cannot read body of http request")
	}
	if len(buf) > 0 {
		if err = jsoniter.ConfigFastest.Unmarshal(buf, &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, nhttp.WrapError(err,
				http.StatusBadRequest,
				fmt.Sprintf("request body '%s': cannot parse non-json request body", buf),
			)
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := core.NewUrlQueryFrom(r.URL.Query())
	_ = queryParams

	parsedQueryParams := make(map[string]bool)
	_ = parsedQueryParams

	err = mjhttp.UnmarshalPathParam(pathParams, &req.Name, "name")
	if err != nil && !core.IsNotFoundError(err) {
		return nil, nhttp.WrapError(err, 400, "cannot unmarshal the name  query parameter")
	}

	return &req, nil
}

// DecodeHTTPCreateFileZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded create_file request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPCreateFileZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	var req pb.CreateFileRequest

	ri := interface{}(&req)
	if decoder, ok := ri.(nhttp.RequestDecoder); ok {
		if err := decoder.DecodeHttpRequest(r); err != nil {
			return nil, nhttp.WrapError(err, 400, fmt.Sprintf("cannot decode the request to CreateFileRequest by customized RequestDecoder, err:%s", err.Error()))
		}
		return &req, nil
	}

	// to support gzip input
	var reader io.ReadCloser
	var err error
	switch r.Header.Get("Content-Encoding") {
	case "gzip":
		reader, err = gzip.NewReader(r.Body)
		defer reader.Close()
		if err != nil {
			return nil, nhttp.WrapError(err, 400, "failed to read the gzip content")
		}
	default:
		reader = r.Body
	}

	buf, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, nhttp.WrapError(err, 400, "cannot read body of http request")
	}
	if len(buf) > 0 {
		req.File = &file.BinaryFile{}
		if err = jsoniter.ConfigFastest.Unmarshal(buf, req.File); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, nhttp.WrapError(err,
				http.StatusBadRequest,
				fmt.Sprintf("request body '%s': cannot parse non-json request body", buf),
			)
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := core.NewUrlQueryFrom(r.URL.Query())
	_ = queryParams

	parsedQueryParams := make(map[string]bool)
	_ = parsedQueryParams

	fileInitialized := false
	if req.File == nil {
		fileInitialized = true
		req.File = &file.BinaryFile{}
	}
	err = mjhttp.UnmarshalQueryParam(queryParams, req.File, "file")
	if err != nil {
		if core.IsNotFoundError(err) {
			if fileInitialized {
				req.File = nil
			}
		} else {
			return nil, nhttp.WrapError(err, 400, "cannot unmarshal the file  query parameter")
		}
	}

	return &req, nil
}

// DecodeHTTPBatchCreateFileZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded batch_create_file request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPBatchCreateFileZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	var req pb.BatchCreateFileRequest

	ri := interface{}(&req)
	if decoder, ok := ri.(nhttp.RequestDecoder); ok {
		if err := decoder.DecodeHttpRequest(r); err != nil {
			return nil, nhttp.WrapError(err, 400, fmt.Sprintf("cannot decode the request to BatchCreateFileRequest by customized RequestDecoder, err:%s", err.Error()))
		}
		return &req, nil
	}

	// to support gzip input
	var reader io.ReadCloser
	var err error
	switch r.Header.Get("Content-Encoding") {
	case "gzip":
		reader, err = gzip.NewReader(r.Body)
		defer reader.Close()
		if err != nil {
			return nil, nhttp.WrapError(err, 400, "failed to read the gzip content")
		}
	default:
		reader = r.Body
	}

	buf, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, nhttp.WrapError(err, 400, "cannot read body of http request")
	}
	if len(buf) > 0 {
		req.Files = []*file.BinaryFile{}
		if err = jsoniter.ConfigFastest.Unmarshal(buf, &req.Files); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, nhttp.WrapError(err,
				http.StatusBadRequest,
				fmt.Sprintf("request body '%s': cannot parse non-json request body", buf),
			)
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := core.NewUrlQueryFrom(r.URL.Query())
	_ = queryParams

	parsedQueryParams := make(map[string]bool)
	_ = parsedQueryParams

	err = mjhttp.UnmarshalQueryParam(queryParams, &req.Files, "files")
	if err != nil && !core.IsNotFoundError(err) {
		return nil, nhttp.WrapError(err, 400, "cannot unmarshal the files  query parameter")
	}

	return &req, nil
}

// EncodeHTTPGenericResponse is a transport/http.EncodeResponseFunc that encodes
// the response as JSON to the response writer. Primarily useful in a server.
func EncodeHTTPGenericResponse(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	if writer, ok := nhttp.BoundResponseWriter(ctx, response); ok {
		return writer.WriteHttpResponse(ctx, w)
	}

	if writer, ok := response.(nhttp.ResponseWriter); ok {
		return writer.WriteHttpResponse(ctx, w)
	}

	if reflect.ValueOf(response).IsNil() {
		response = nil
	}
	if _, ok := response.(*core.Null); ok {
		response = nil
	}

	enveloped := nhttp.IsEnvelopeStyle(ctx, cfg.GetStyle())
	if enveloped {
		code := core.NewErrorCode(200)
		message := "OK"
		if sc := cfg.GetEnvelop().SuccessCode; len(sc) > 0 {
			if c, err := core.ParseErrorCode(sc); err != nil {
				logs.Warnw("failed to parse the user setting success code, will use \"200\" indeed.", "code", sc, "error", err)
			} else {
				code = c
			}
		}
		if msg := cfg.GetEnvelop().SuccessMessage; len(msg) > 0 {
			message = msg
		}

		if response == nil {
			response = &nhttp.EnvelopedResponse{
				Error: &core.Error{
					Code:    code,
					Message: message,
				},
			}
		} else {
			totalCount := int32(0)
			nextPageToken := ""
			if p, ok := response.(pagination.Paginater); ok {
				totalCount = p.GetTotalCount()
				nextPageToken = p.GetNextPageToken()
			}

			response = &nhttp.EnvelopedResponse{
				Error: &core.Error{
					Code:    code,
					Message: message,
				},
				TotalCount:    totalCount,
				NextPageToken: nextPageToken,
				Data:          response,
			}
		}
	} else if response != nil {
		if p, ok := response.(pagination.Paginater); ok {
			total := p.GetTotalCount()
			if total > 0 {
				w.Header().Set("X-Total-Count", strconv.Itoa(int(total)))
			}

			next := p.GetNextPageToken()
			if len(next) > 0 {
				path, _ := ctx.Value("http-request-path").(string)
				if len(path) == 0 {
					path = "/?next-page-token=" + next
				} else {
					url, _ := core.ParseUrl(path)
					url.Query.Add("next-page-token", next)
					path = url.Format()
				}
				w.Header().Set("Link", fmt.Sprintf("<%s>; rel=\"next\"", path))
			}
		}
	}

	if response == nil {
		return nil
	}

	return nhttp.NewResponseJsonWriter(response).WriteHttpResponse(ctx, w)
}

// Helper functions

func headersToContext(ctx context.Context, r *http.Request) context.Context {
	for k, _ := range r.Header {
		// The key is added both in http format (k) which has had
		// http.CanonicalHeaderKey called on it in transport as well as the
		// strings.ToLower which is the grpc metadata format of the key so
		// that it can be accessed in either format
		ctx = context.WithValue(ctx, k, r.Header.Get(k))
		ctx = context.WithValue(ctx, strings.ToLower(k), r.Header.Get(k))
	}

	// add the access key to context
	accessKey := r.URL.Query().Get("access_key")
	if len(accessKey) > 0 {
		ctx = context.WithValue(ctx, "access_key", accessKey)
	}

	// Authorization header
	if auth := r.Header.Get("Authorization"); len(auth) > 0 {
		if strings.HasPrefix(auth, "Bearer") {
			auth = strings.TrimSpace(strings.TrimPrefix(auth, "Bearer"))
			ctx = context.WithValue(ctx, "bearer_token", auth)
		} else if strings.HasPrefix(auth, "Basic") {
			auth = strings.TrimSpace(strings.TrimPrefix(auth, "Basic"))
			ctx = context.WithValue(ctx, "basic_token", auth)
		}
	}

	// Authorization cookie
	if cookie, err := r.Cookie("auth_token"); err == nil && cookie != nil {
		ctx = context.WithValue(ctx, "auth_token", cookie.Value)
	}

	// Tune specific change.
	// also add the request url
	ctx = context.WithValue(ctx, "http-request-path", r.URL.Path)
	ctx = context.WithValue(ctx, "http-request-query", r.URL.Query())
	ctx = context.WithValue(ctx, "transport", "HTTPJSON")

	return ctx
}

func queryToContext(ctx context.Context, r *http.Request) context.Context {
	check := func(values []string) bool {
		for _, value := range values {
			if value == "true" {
				return true
			}
		}
		return false
	}
	for key, values := range r.URL.Query() {
		switch key {
		case "envelope":
			if check(values) {
				ctx = context.WithValue(ctx, "envelope", true)
			}
		}
	}
	return ctx
}
