// Code generated by mojo. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: armory/unitable/db_query.proto

package unitable

import (
	_ "github.com/mojo-lang/core/go/pkg/mojo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DbQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sql     string         `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	Columns DbQueryColumns `protobuf:"bytes,15,rep,name=columns,proto3" json:"columns,omitempty" db:"columns,json"`
}
type DbQueryColumns []*Column

func (x *DbQuery) Reset() {
	*x = DbQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_armory_unitable_db_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbQuery) ProtoMessage() {}

func (x *DbQuery) ProtoReflect() protoreflect.Message {
	mi := &file_armory_unitable_db_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbQuery.ProtoReflect.Descriptor instead.
func (*DbQuery) Descriptor() ([]byte, []int) {
	return file_armory_unitable_db_query_proto_rawDescGZIP(), []int{0}
}

func (x *DbQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DbQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DbQuery) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *DbQuery) GetColumns() DbQueryColumns {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_armory_unitable_db_query_proto protoreflect.FileDescriptor

var file_armory_unitable_db_query_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x2f, 0x64, 0x62, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x1a, 0x1c, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0f, 0x6d, 0x6f, 0x6a, 0x6f, 0x2f, 0x6d, 0x6f, 0x6a, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7c, 0x0a, 0x07, 0x44, 0x62, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71,
	0x6c, 0x12, 0x3b, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x0f, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x75, 0x6e, 0x69, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x08, 0xda, 0xcf, 0x24,
	0x00, 0xe8, 0xd5, 0x24, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x42, 0x68,
	0x0a, 0x19, 0x69, 0x6f, 0x2e, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x61, 0x72, 0x6d, 0x6f,
	0x72, 0x79, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x0c, 0x44, 0x62, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2d, 0x69,
	0x6f, 0x2f, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x72, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x3b,
	0x75, 0x6e, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_armory_unitable_db_query_proto_rawDescOnce sync.Once
	file_armory_unitable_db_query_proto_rawDescData = file_armory_unitable_db_query_proto_rawDesc
)

func file_armory_unitable_db_query_proto_rawDescGZIP() []byte {
	file_armory_unitable_db_query_proto_rawDescOnce.Do(func() {
		file_armory_unitable_db_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_armory_unitable_db_query_proto_rawDescData)
	})
	return file_armory_unitable_db_query_proto_rawDescData
}

var file_armory_unitable_db_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_armory_unitable_db_query_proto_goTypes = []interface{}{
	(*DbQuery)(nil), // 0: armory.unitable.DbQuery
	(*Column)(nil),  // 1: armory.unitable.Column
}
var file_armory_unitable_db_query_proto_depIdxs = []int32{
	1, // 0: armory.unitable.DbQuery.columns:type_name -> armory.unitable.Column
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_armory_unitable_db_query_proto_init() }
func file_armory_unitable_db_query_proto_init() {
	if File_armory_unitable_db_query_proto != nil {
		return
	}
	file_armory_unitable_column_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_armory_unitable_db_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_armory_unitable_db_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_armory_unitable_db_query_proto_goTypes,
		DependencyIndexes: file_armory_unitable_db_query_proto_depIdxs,
		MessageInfos:      file_armory_unitable_db_query_proto_msgTypes,
	}.Build()
	File_armory_unitable_db_query_proto = out.File
	file_armory_unitable_db_query_proto_rawDesc = nil
	file_armory_unitable_db_query_proto_goTypes = nil
	file_armory_unitable_db_query_proto_depIdxs = nil
}
