// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armory/unitable/column.proto

package io.ncraft.armory.unitable;

public interface ColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:armory.unitable.Column)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string database = 2 [(.mojo.db_index) = ""];</code>
   * @return The database.
   */
  java.lang.String getDatabase();
  /**
   * <code>string database = 2 [(.mojo.db_index) = ""];</code>
   * @return The bytes for database.
   */
  com.google.protobuf.ByteString
      getDatabaseBytes();

  /**
   * <code>string table_id = 3 [(.mojo.db_index) = ""];</code>
   * @return The tableId.
   */
  java.lang.String getTableId();
  /**
   * <code>string table_id = 3 [(.mojo.db_index) = ""];</code>
   * @return The bytes for tableId.
   */
  com.google.protobuf.ByteString
      getTableIdBytes();

  /**
   * <code>string name = 4 [(.mojo.db_index) = ""];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4 [(.mojo.db_index) = ""];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string display_name = 5;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 5;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string export_name = 6;</code>
   * @return The exportName.
   */
  java.lang.String getExportName();
  /**
   * <code>string export_name = 6;</code>
   * @return The bytes for exportName.
   */
  com.google.protobuf.ByteString
      getExportNameBytes();

  /**
   * <code>string group_display_name = 7;</code>
   * @return The groupDisplayName.
   */
  java.lang.String getGroupDisplayName();
  /**
   * <code>string group_display_name = 7;</code>
   * @return The bytes for groupDisplayName.
   */
  com.google.protobuf.ByteString
      getGroupDisplayNameBytes();

  /**
   * <code>string type = 8;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 8;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string format = 9;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 9;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>bool indexed = 10;</code>
   * @return The indexed.
   */
  boolean getIndexed();

  /**
   * <code>bool unique = 11;</code>
   * @return The unique.
   */
  boolean getUnique();

  /**
   * <code>bool show = 12;</code>
   * @return The show.
   */
  boolean getShow();

  /**
   * <code>bool editable = 13;</code>
   * @return The editable.
   */
  boolean getEditable();

  /**
   * <code>bool filterable = 14;</code>
   * @return The filterable.
   */
  boolean getFilterable();

  /**
   * <code>bool temporal = 15;</code>
   * @return The temporal.
   */
  boolean getTemporal();

  /**
   * <code>bool dimensional = 16;</code>
   * @return The dimensional.
   */
  boolean getDimensional();

  /**
   * <code>string referenced = 20;</code>
   * @return The referenced.
   */
  java.lang.String getReferenced();
  /**
   * <code>string referenced = 20;</code>
   * @return The bytes for referenced.
   */
  com.google.protobuf.ByteString
      getReferencedBytes();

  /**
   * <code>.mojo.core.Value example = 30;</code>
   * @return Whether the example field is set.
   */
  boolean hasExample();
  /**
   * <code>.mojo.core.Value example = 30;</code>
   * @return The example.
   */
  org.mojolang.mojo.core.Value getExample();
  /**
   * <code>.mojo.core.Value example = 30;</code>
   */
  org.mojolang.mojo.core.ValueOrBuilder getExampleOrBuilder();

  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   * @return The createTime.
   */
  org.mojolang.mojo.core.Timestamp getCreateTime();
  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   * @return The updateTime.
   */
  org.mojolang.mojo.core.Timestamp getUpdateTime();
  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getUpdateTimeOrBuilder();
}
