// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armory/unitable/db_query.proto

package io.ncraft.armory.unitable;

public interface DbQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:armory.unitable.DbQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sql = 3;</code>
   * @return The sql.
   */
  java.lang.String getSql();
  /**
   * <code>string sql = 3;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <code>repeated string parameters = 4;</code>
   * @return A list containing the parameters.
   */
  java.util.List<java.lang.String>
      getParametersList();
  /**
   * <code>repeated string parameters = 4;</code>
   * @return The count of parameters.
   */
  int getParametersCount();
  /**
   * <code>repeated string parameters = 4;</code>
   * @param index The index of the element to return.
   * @return The parameters at the given index.
   */
  java.lang.String getParameters(int index);
  /**
   * <code>repeated string parameters = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameters at the given index.
   */
  com.google.protobuf.ByteString
      getParametersBytes(int index);

  /**
   * <code>string table = 5;</code>
   * @return The table.
   */
  java.lang.String getTable();
  /**
   * <code>string table = 5;</code>
   * @return The bytes for table.
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>repeated .armory.unitable.Column columns = 15 [(.mojo.reference) = "", (.mojo.db_json) = true];</code>
   */
  java.util.List<io.ncraft.armory.unitable.Column> 
      getColumnsList();
  /**
   * <code>repeated .armory.unitable.Column columns = 15 [(.mojo.reference) = "", (.mojo.db_json) = true];</code>
   */
  io.ncraft.armory.unitable.Column getColumns(int index);
  /**
   * <code>repeated .armory.unitable.Column columns = 15 [(.mojo.reference) = "", (.mojo.db_json) = true];</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .armory.unitable.Column columns = 15 [(.mojo.reference) = "", (.mojo.db_json) = true];</code>
   */
  java.util.List<? extends io.ncraft.armory.unitable.ColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .armory.unitable.Column columns = 15 [(.mojo.reference) = "", (.mojo.db_json) = true];</code>
   */
  io.ncraft.armory.unitable.ColumnOrBuilder getColumnsOrBuilder(
      int index);
}
