db:
  driver: postgres
  dsn: postgresql://localhost:5432/unitable
  debug: true
  maxIdleConnections: 0
  maxOpenConnections: 0
dataDB:
  driver: postgres
  dsn: postgresql://localhost:5432/unidata
  debug: true
  maxIdleConnections: 0
  maxOpenConnections: 0