db:
  driver: postgres
  dsn: postgresql://postgres:daju@2024!@localhost:5432/unitable
  debug: false
  maxIdleConnections: 0
  maxOpenConnections: 0
dataDB:
  default: residence
  dbs:
    residence:
      driver: postgres
      dsn: postgresql://postgres:daju@2024!@localhost:5432/residence
      debug: true
      maxIdleConnections: 0
      maxOpenConnections: 0
    xddigital:
      driver: postgres
      dsn: postgresql://postgres:daju@2024!@localhost:5433/xddigital
      debug: true
      maxIdleConnections: 0
      maxOpenConnections: 0