// Code generated by mojo. DO NOT EDIT.

package file_client

import (
	"context"
	"fmt"
	"github.com/go-kit/kit/endpoint"
	file "github.com/ncraft-io/armory/go/pkg/armory/file"
	pb "github.com/ncraft-io/armory/go/pkg/armory/file/v1"
)

// Client is the transport-independent unary API implemented by HTTP and gRPC clients.
type Client interface {
	GetFile(context.Context, *pb.GetFileRequest) (*file.BinaryFile, error)
	CreateFile(context.Context, *pb.CreateFileRequest) (*file.BinaryFile, error)
	BatchCreateFile(context.Context, *pb.BatchCreateFileRequest) (*pb.BatchCreateFileResponse, error)
}

type Endpoints struct {
	GetFileEndpoint         endpoint.Endpoint
	CreateFileEndpoint      endpoint.Endpoint
	BatchCreateFileEndpoint endpoint.Endpoint
}

var _ Client = Endpoints{}
var _ = fmt.Errorf
var _ context.Context
var _ endpoint.Endpoint

func (e Endpoints) GetFile(ctx context.Context, request *pb.GetFileRequest) (*file.BinaryFile, error) {
	if request == nil {
		return nil, fmt.Errorf("GetFile: nil request")
	}
	if e.GetFileEndpoint == nil {
		return nil, fmt.Errorf("GetFile: endpoint is not configured")
	}
	result, err := e.GetFileEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*file.BinaryFile)
	if !ok || response == nil {
		return nil, fmt.Errorf("GetFile: invalid response type %T", result)
	}
	return response, nil
}

func MakeGetFileEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetFileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetFile: invalid request type %T", request)
		}
		return client.GetFile(ctx, req)
	}
}

func (e Endpoints) CreateFile(ctx context.Context, request *pb.CreateFileRequest) (*file.BinaryFile, error) {
	if request == nil {
		return nil, fmt.Errorf("CreateFile: nil request")
	}
	if e.CreateFileEndpoint == nil {
		return nil, fmt.Errorf("CreateFile: endpoint is not configured")
	}
	result, err := e.CreateFileEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*file.BinaryFile)
	if !ok || response == nil {
		return nil, fmt.Errorf("CreateFile: invalid response type %T", result)
	}
	return response, nil
}

func MakeCreateFileEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateFileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateFile: invalid request type %T", request)
		}
		return client.CreateFile(ctx, req)
	}
}

func (e Endpoints) BatchCreateFile(ctx context.Context, request *pb.BatchCreateFileRequest) (*pb.BatchCreateFileResponse, error) {
	if request == nil {
		return nil, fmt.Errorf("BatchCreateFile: nil request")
	}
	if e.BatchCreateFileEndpoint == nil {
		return nil, fmt.Errorf("BatchCreateFile: endpoint is not configured")
	}
	result, err := e.BatchCreateFileEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*pb.BatchCreateFileResponse)
	if !ok || response == nil {
		return nil, fmt.Errorf("BatchCreateFile: invalid response type %T", result)
	}
	return response, nil
}

func MakeBatchCreateFileEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchCreateFileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchCreateFile: invalid request type %T", request)
		}
		return client.BatchCreateFile(ctx, req)
	}
}
