components:
  schemas:
    armory.auth.Account:
      title: armory.auth.Account
      type: object
    armory.unitable.Column:
      description: unitable的列的元信息
      properties:
        createTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        database:
          description: 所属的表单所在的数据库名称
          title: mojo.core.String
          type: string
        dimensional:
          description: 是否是维度相关的，即可枚举的值
          title: mojo.core.Bool
          type: boolean
        displayName:
          description: 可以是显示中文的名称
          title: mojo.core.String
          type: string
        editable:
          description: 字段是否可编辑，控制前端显示时，允许用户编辑，实际可否编辑还得检查相应权限
          title: mojo.core.Bool
          type: boolean
        exportName:
          description: 导出时使用的名称，比如Excel导出时
          title: mojo.core.String
          type: string
        filterable:
          description: 字段能够进行过滤操作
          title: mojo.core.Bool
          type: boolean
        format:
          description: 当列为String时，指定更详细的类型，比如时间、几何等
          title: mojo.core.String
          type: string
        groupDisplayName:
          description: 所属的列的组合名称
          title: mojo.core.String
          type: string
        id:
          description: 列的ID
          title: mojo.core.String
          type: string
        indexed:
          description: 是否需要被索引
          title: mojo.core.Bool
          type: boolean
        name:
          description: 表单的列名，符合数据库的列名规格，采用 `[a-z][a-z_0-9]*` 规格
          title: mojo.core.String
          type: string
        referenced:
          description: 是否为引用字段，可以设置是否自动join
          title: mojo.core.String
          type: string
        show:
          description: 是否需要显示
          title: mojo.core.Bool
          type: boolean
        tableId:
          description: 所属的表单名
          title: mojo.core.String
          type: string
        temporal:
          description: 是否是临时的
          title: mojo.core.Bool
          type: boolean
        type:
          description: 列的数据库类型 "integer", "number", "string"
          title: mojo.core.String
          type: string
        unique:
          description: 是否需要在表内是唯一的
          title: mojo.core.Bool
          type: boolean
        updateTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
      title: armory.unitable.Column
      type: object
    armory.unitable.Table:
      description: 动态table的元信息
      properties:
        columns:
          description: 表单包含的列的元信息
          items:
            $ref: '#/components/schemas/armory.unitable.Column'
          title: mojo.core.Array
          type: array
        createTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
        database:
          description: 表单所在的数据库名
          title: mojo.core.String
          type: string
        displayName:
          description: 可以是显示中文的名称
          title: mojo.core.String
          type: string
        exportName:
          description: 导出时使用的名称，比如Excel导出时，作为sheet名称
          title: mojo.core.String
          type: string
        id:
          description: 表单ID
          title: mojo.core.String
          type: string
        name:
          description: 表单名
          title: mojo.core.String
          type: string
        tenant:
          description: 租户名
          title: mojo.core.String
          type: string
        updateTime:
          $ref: '#/components/schemas/mojo.core.Timestamp'
      title: armory.unitable.Table
      type: object
    mojo.core.FieldMask:
      description: ""
      format: FieldMask
      title: mojo.core.FieldMask
      type: string
    mojo.core.Object:
      description: Object type
      title: mojo.core.Object
      type: object
    mojo.core.Ordering:
      title: mojo.core.Ordering
      type: object
    mojo.core.Timestamp:
      description: ""
      format: Timestamp
      title: mojo.core.Timestamp
      type: string
info:
  description: ""
  title: 权限管理服务
  version: 0.1.0
openapi: 3.0.3
paths:
  armory/auth/v1/accounts:
    post:
      description: ""
      operationId: create_account
      parameters:
      - in: query
        name: database
        schema:
          title: mojo.core.String
          type: string
      - in: query
        name: table
        schema:
          title: mojo.core.String
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/armory.auth.Account'
          description: OK
      summary: 创建账号
